- Help message was added in get-latest-ocs-live-ver. - The options of genisoimage in ocs-iso was rearranged. - Rearranging the options for genisoimage in create-drbl-live and create-gparted-live so that isolinux 5.10 could boot on some real machine. Besides, not all included files are used with -graft-points. This is the key point for the workaround.

diff --git a/bin/get-latest-ocs-live-ver b/bin/get-latest-ocs-live-ver
--- a/bin/get-latest-ocs-live-ver
+++ b/bin/get-latest-ocs-live-ver
@@ -28,10 +28,27 @@ query_branch() {
 }
 #
 USAGE() {
-  echo "Usage: $0 branch" 1>&2
+  echo "$ocs - To get the latest Clonezilla live version number on file release repository"
+  echo "Usage: $ocs branch" 1>&2
   echo "Where branch is one of:" 1>&2
   echo "$branches" 1>&2
 }
+
+#
+####################
+### Main program ###
+####################
+
+ocs=`basename $0`
+#
+while [ $# -gt 0 ]; do
+ case "$1" in
+   -*)     echo "${0}: ${1}: invalid option" >&2
+           USAGE >& 2
+           exit 2 ;;
+   *)      break ;;
+ esac
+done
 
 branch="$1"
 if [ -z "$branch" ]; then
