Fixed 'box' partition device error.
Fixed 'box' partition device error when empty
Partition Devices (NUMDEV=0).
Ref: https://sourceforge.net/p/clonezilla/bugs/442/

diff --git a/scripts/sbin/ocs-functions b/scripts/sbin/ocs-functions
--- a/scripts/sbin/ocs-functions
+++ b/scripts/sbin/ocs-functions
@@ -4897,8 +4897,8 @@ get_input_dev_name() {
           if [ "$ocs_sr_type" = "restoreparts" ]; then
             # only when running restoreparts
             gen_proc_partitions_map_file
-            if [ -n "$(get_part_list $partition_table)" ]; then
-              # If exists in /proc/partitions, let's create the partition table
+            if [ -z "$(get_part_list $partition_table)" ]; then
+              # If no partitions exist in /proc/partitions, let's create the partition table
               [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
               echo "$msg_no_partition_table_need_to_create"
 	      echo "$msg_enter_another_shell_for_fdisk"
@@ -4907,6 +4907,32 @@ get_input_dev_name() {
               read
               /bin/bash
               get_not_busy_disks_or_parts $dev_type "" "$dev_to_be_exclude"  # we will get dev_list
+              # Recalculate NUMDEV
+              NUMDEV=0
+              for p in $dev_list; do
+                # skip swap and extended partition
+                FILE="$(LC_ALL=C ocs-get-dev-info "/dev/$p" type filesystem parttype 2>/dev/null | tr [:upper:] [:lower:])"
+                rc=$?
+                if [ "$rc" = "0" ]; then
+                  [ -n "$(echo $FILE | grep -Eiw "(extended|0x5|0xf)")" ] && continue
+                fi
+                if [ "$skip_lvm_raid" = "yes" ]; then
+                  if is_block_device_with_fs /dev/$p; then
+                    [ "$rc" = "0" ] && case "$FILE" in *lvm*|*raid*) continue ;; esac
+                  fi
+                fi
+                NUMDEV=$[NUMDEV+1]
+              done
+            fi
+            [ -f "$partition_table" ] && rm -f $partition_table
+            # If NUMDEV is still 0 (even if they didn't create partition, or it was not empty but NUMDEV is 0)
+            if [ $NUMDEV -le 0 ]; then
+              [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+              echo "$msg_error! $msg_not_mounted_dev_found"
+              echo -n "$msg_press_enter_to_exit"
+              read
+              [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+              exit 1
             fi
           else
             [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
