- Giving more specific error messages when searching the unmounted partitions in get_input_dev_name.

diff --git a/scripts/sbin/ocs-functions b/scripts/sbin/ocs-functions
--- a/scripts/sbin/ocs-functions
+++ b/scripts/sbin/ocs-functions
@@ -4138,6 +4138,13 @@ get_input_dev_name() {
               /bin/bash
               get_not_busy_disks_or_parts $dev_type "" "$dev_to_be_exclude"  # we will get dev_list
             fi
+          else
+            [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+            echo "$msg_error! $msg_not_mounted_dev_found"
+            echo -n "$msg_press_enter_to_exit"
+            read
+            [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+            exit 1
           fi
           ;;
       esac
