- The info to be shown in the TUI mod of countdown_or_confirm_before_restore was improved. More info will be shown.

diff --git a/scripts/sbin/ocs-functions b/scripts/sbin/ocs-functions
--- a/scripts/sbin/ocs-functions
+++ b/scripts/sbin/ocs-functions
@@ -35,12 +35,37 @@ confirm_continue_or_default_quit() {
 #
 confirm_continue_no_default_answer() {
   local ans_ ans_continue continue_choice
-  local job_before_quit="$1"
+  local job_before_quit job_des
   continue_choice=""
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -d|--description)
+         shift
+         if [ -z "$(echo $1 |grep ^-.)" ]; then
+           # skip the -xx option, in case 
+           job_des="$1"
+           shift
+         fi
+         if [ -z "$job_des" ]; then
+           echo "-d is used, but no job_des assigned."
+           echo "$msg_program_stop"
+           [ "$save_restore_error_log" = "yes" ] && copy_error_log
+           exit 1
+         fi
+         ;;
+      -*)     echo "${0}: ${1}: invalid option"
+              echo "$msg_program_stop"
+              [ "$save_restore_error_log" = "yes" ] && copy_error_log
+              exit 2 ;;
+      *)      break ;;
+    esac
+  done
+  job_before_quit="$1"
   while [ -z "$continue_choice" ]; do
    if [ "$messages_shown_preference" = "tui" ]; then
+     # Because dialog/whiptail "--yesno" must have a yes or no, we choose no here.
      $DIA --backtitle "$msg_nchc_free_software_labs" --title "$msg_nchc_clonezilla" \
-     --yesno "$msg_are_u_sure_u_want_to_continue" 0 0 
+     --defaultno --yesno "${job_des}${msg_are_u_sure_u_want_to_continue}" 0 0 
      ans_="$?"
      # Convert ans_ to ans_continue
      case "$ans_" in
@@ -3068,13 +3093,44 @@ warning_about_run_parts_in_debian() {
 } # end of warning_about_run_parts_in_debian
 #
 countdown_or_confirm_before_restore() {
-  local restore_img_name="$1"
-  local new_dev_to_be_restore="$2"
-  local i partition_table
+  local restore_img_name new_dev_to_be_restore
+  local i partition_table ctdn rest_conf init_des
   local continue_choice
   # wait for some commands if specified by user
+  # init_des is the 1st line description used in confirming
 
-  if [ -n "$TIME_to_wait" ]; then
+  # Default settings
+  ctdn="yes"
+  rest_conf="yes"
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -s|--skip-countdown) shift; ctdn="no" ;;
+      -m|--skip-confirm) shift; rest_conf="no" ;;
+      -i|--init-description)
+         shift
+         if [ -z "$(echo $1 |grep ^-.)" ]; then
+           # skip the -xx option, in case 
+           init_des="$1"
+           shift
+         fi
+         if [ -z "$init_des" ]; then
+           echo "-i is used, but no init_des assigned."
+           echo "$msg_program_stop"
+           [ "$save_restore_error_log" = "yes" ] && copy_error_log
+           exit 1
+         fi
+         ;;
+      -*)     echo "${0}: ${1}: invalid option"
+              echo "$msg_program_stop"
+              [ "$save_restore_error_log" = "yes" ] && copy_error_log
+              exit 2 ;;
+      *)      break ;;
+    esac
+  done
+  restore_img_name="$1"
+  new_dev_to_be_restore="$2"
+
+  if [ -n "$TIME_to_wait" ] && [ "$ctdn" = "yes" ]; then
     n="$TIME_to_wait"
     echo $msg_delimiter_star_line | tee -a $OCS_LOGFILE
     echo "$msg_the_following_step_is_to_restore_img_to_disk_part: \"$restore_img_name\" -> \"$new_dev_to_be_restore\"" | tee -a $OCS_LOGFILE
@@ -3093,22 +3149,36 @@ countdown_or_confirm_before_restore() {
     echo "Last chance to quit in $TIME_to_wait seconds... Press Shutdown button in this machine to avoid continuing." | tee --append $OCS_LOGFILE
     countdown $TIME_to_wait
   fi
-  if [ "$confirm_before_clone" = "yes" ]; then
+  if [ "$confirm_before_clone" = "yes" ] && [ "$rest_conf" = "yes" ]; then
     echo $msg_delimiter_star_line | tee -a $OCS_LOGFILE
-    echo "$msg_the_following_step_is_to_restore_img_to_disk_part: \"$restore_img_name\" -> \"$new_dev_to_be_restore\"" | tee --append $OCS_LOGFILE
-    [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-    if [ "$ocs_sr_type" = "restoreparts" -a "$create_part" = "yes" ]; then
-      echo "$msg_uppercase_Warning. $msg_option_k_is_not_chosen_part_table_will_be_recreated" | tee --append $OCS_LOGFILE
+    if [ "$messages_shown_preference" = "tui" ]; then
+      # TUI mode
+      tui_prompt_txt="${init_des}${msg_the_following_step_is_to_restore_img_to_disk_part}: \"$restore_img_name\" -> \"$new_dev_to_be_restore\"\n"
+      if [ "$ocs_sr_type" = "restoreparts" -a "$create_part" = "yes" ]; then
+        tui_prompt_txt="${tui_prompt_txt}$msg_uppercase_Warning. $msg_option_k_is_not_chosen_part_table_will_be_recreated\n"
+      fi
+      tui_prompt_txt="${tui_prompt_txt}$msg_uppercase_Warning!!! $msg_uppercase_Warning!!! $msg_uppercase_Warning!!!\n"
+      if [ -n "$dev_model_shown" ]; then
+        tui_prompt_txt="${tui_prompt_txt}$msg_delimiter_star_line\n$msg_all_data_in_dev_will_be_overwritten:\n$dev_model_shown\n$msg_delimiter_star_line\n"
+      fi
+      confirm_continue_no_default_answer -d "$tui_prompt_txt"
+    else
+      # CMD mode, no TUI
+      echo "${init_des}${msg_the_following_step_is_to_restore_img_to_disk_part}: \"$restore_img_name\" -> \"$new_dev_to_be_restore\"" | tee --append $OCS_LOGFILE
+      [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+      if [ "$ocs_sr_type" = "restoreparts" -a "$create_part" = "yes" ]; then
+        echo "$msg_uppercase_Warning. $msg_option_k_is_not_chosen_part_table_will_be_recreated" | tee --append $OCS_LOGFILE
+      fi
+      echo "$msg_uppercase_Warning!!! $msg_uppercase_Warning!!! $msg_uppercase_Warning!!!"
+      if [ -n "$dev_model_shown" ]; then
+        echo "$msg_uppercase_Warning. $msg_all_data_in_dev_will_be_overwritten:" | tee --append $OCS_LOGFILE
+        echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
+        echo -e "$dev_model_shown" | tee --append $OCS_LOGFILE
+        echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
+      fi
+      [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+      confirm_continue_no_default_answer
     fi
-    echo "$msg_uppercase_Warning!!! $msg_uppercase_Warning!!! $msg_uppercase_Warning!!!"
-    if [ -n "$dev_model_shown" ]; then
-      echo "$msg_uppercase_Warning. $msg_all_data_in_dev_will_be_overwritten:" | tee --append $OCS_LOGFILE
-      echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
-      echo -e "$dev_model_shown" | tee --append $OCS_LOGFILE
-      echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
-    fi
-    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-    confirm_continue_no_default_answer
   fi
 } # end of countdown_or_confirm_before_restore
 #
@@ -7293,56 +7363,8 @@ task_restoreparts() {
   rc=$?
   if [ "$rc" -gt 0 -a "$ocs_batch_mode" != "on" ]; then
     echo "This program is not started by clonezilla server." | tee --append $OCS_LOGFILE
-    echo "$msg_the_following_step_is_to_restore_img_to_disk_part: \"$target_dir_fullpath\" -> \"$target_hd ($target_parts)\"" | tee --append $OCS_LOGFILE
-    [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-    if [ "$ocs_sr_type" = "restoreparts" -a "$create_part" = "yes" ]; then
-      echo "$msg_uppercase_Warning! $msg_option_k_is_not_chosen_part_table_will_be_recreated" | tee --append $OCS_LOGFILE
-    fi
-    echo "$msg_uppercase_Warning!!! $msg_uppercase_Warning!!! $msg_uppercase_Warning!!!" | tee --append $OCS_LOGFILE
-    if [ -n "$dev_model_shown" ]; then
-      echo "$msg_uppercase_Warning! $msg_all_data_in_dev_will_be_overwritten:" | tee --append $OCS_LOGFILE
-      echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
-      echo -e "$dev_model_shown" | tee --append $OCS_LOGFILE
-      echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
-    fi
-    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-    continue_choice=""
-    while [ -z "$continue_choice" ]; do
-      if [ "$messages_shown_preference" = "tui" ]; then
-        $DIA --backtitle "$msg_nchc_free_software_labs" --title "$msg_nchc_clonezilla" \
-        --yesno "$msg_let_me_ask_you_again. $msg_are_u_sure_u_want_to_continue" 0 0 
-        ans_="$?"
-        # Convert ans_ to ans_continue
-        case "$ans_" in
-          0) # yes is chosen
-             continue_restore="yes";;
-          1) # no is chosen
-             continue_restore="no";;
-        esac
-      else
-        echo "$msg_let_me_ask_you_again. $msg_are_u_sure_u_want_to_continue" | tee --append $OCS_LOGFILE
-        echo -n "[y/n] " | tee --append $OCS_LOGFILE
-        read continue_restore
-      fi
-      case "$continue_restore" in
-       y|Y|[yY][eE][sS])
-         continue_choice="yes"
-         echo "$msg_ok_let_do_it!" | tee --append $OCS_LOGFILE
-         ;;
-       n|N|[nN][oO])
-         continue_choice="no"
-         rm_tmp_cnvt_img
-         echo "$msg_program_stop!" | tee --append $OCS_LOGFILE
-         exit 1
-         ;;
-       *)
-         [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-         echo "$msg_you_have_to_enter_yes_or_no!" | tee --append $OCS_LOGFILE
-         [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-         echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
-         ;;
-      esac
-    done
+    #
+    countdown_or_confirm_before_restore -s -i "$msg_let_me_ask_you_again.\n" "$target_dir_fullpath" "$target_hd $target_parts"
   fi
 
   if [ "$create_part" = "yes" ]; then
