Support GRUB EFI NB for EFI network boot clients.
File system overlay was added as one of the known file systems
in prep-ocsroot.
A better mechanism was used to parse the boot parameters in
ocs-run so that it could deal with that from grub efi network booting.
Bug fixed: set-netboot-1st-efi-nvram failed to keep uEFI network
Bug fixed: ocs-resize-part failed to run resize program for
parted >= 3.

diff --git a/scripts/sbin/ocs-functions b/scripts/sbin/ocs-functions
--- a/scripts/sbin/ocs-functions
+++ b/scripts/sbin/ocs-functions
@@ -6178,6 +6178,7 @@ check_target_parts() {
 stop_ocs_service() {
   local to_gen_ssi_files="$1"
   local IP ihost
+  local pxecfg grubcfg pxecfg_MAC grubcfg_MAC
   # check if "ocsmgrd" is running ?
   if [ ! -e "$ocs_lock_dir/clonezilla.lock" ]; then 
     [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
@@ -6216,6 +6217,9 @@ stop_ocs_service() {
     remove_opt_in_pxelinux_cfg_block Clonezilla-live ocs_live_run
   else
     remove_opt_in_pxelinux_cfg_block clonezilla ocs_opt
+    remove_opt_in_grub_efi_cfg_block "--id clonezilla-se-client" ocs_opt
+    # Because there is no way to hide the clonezilla menuentry in grub.cfg, here we have to update the description.
+    force_grub_efi_clients_boot_label clonezilla-se-client "Clonezilla"
   fi
   # prepare the HOSTNAME-IP-MAC table
   OCS_TMP=`mktemp /tmp/ocs_clean_tmp.XXXXXX`
@@ -6231,14 +6235,19 @@ stop_ocs_service() {
     fi
     echo "Stop OCS mode for node $IP, no matter it's in OCS mode or not."
     [ -f "$ihost/etc/inittab.ocs" ] && mv -f $ihost/etc/inittab.ocs $ihost/etc/inittab
-    # remove the pxe config file in $pxecfg_pd/tftpboot/pxelinux.cfg (IP-based)
+    # Remove the pxe config file in $pxecfg_pd/pxelinux.cfg/ (IP-based), like C0A84601
+    # Remove the GRUB uEFI NB config file in $pxecfg_pd/grub-efi.cfg/ (IP-based), like grub.cfg-C0A84601
     pxecfg="$(drbl-gethostip $IP)"
+    grubcfg="grub.cfg-""$pxecfg"
     [ -f "$PXELINUX_DIR/$pxecfg" ] && rm -f $PXELINUX_DIR/$pxecfg
+    [ -f "$GRUB_EFINB_DIR/$grubcfg" ] && rm -f $GRUB_EFINB_DIR/$grubcfg
 
     # HOST_OPTION_MODIFY: maybe it's not IP based, it's MAC based.
     # These files look like: 01-MAC address (with ":" -> "-"),
     pxecfg_MAC="01-$(grep ${ihost##*/} $OCS_TMP | awk -F" " '{print $3}' | tr ":" "-")"
+    grubcfg_MAC="grub.cfg-""$pxecfg_MAC"
     [ -f "$PXELINUX_DIR/$pxecfg_MAC" ] && rm -f $PXELINUX_DIR/$pxecfg_MAC
+    [ -f "$GRUB_EFINB_DIR/$grubcfg_MAC" ] && rm -f $GRUB_EFINB_DIR/$grubcfg_MAC
 
     # remove the stalled ocs-run.param.
     rm -f $drblroot/$IP/etc/ocs/ocs-run.param
@@ -6439,18 +6448,23 @@ start_ocs_service() {
     force_pxe_clients_boot_label Clonezilla-live "$clonezilla_client_menu_label_prefix: $ocs_menu_label"
   else
     force_pxe_clients_boot_label clonezilla "$clonezilla_client_menu_label_prefix: $ocs_menu_label"
+    force_grub_efi_clients_boot_label clonezilla-se-client "$clonezilla_client_menu_label_prefix: $ocs_menu_label"
   fi
   # set runlevel 1 to kernel parameter in pxelinux config
   add_runlevel_1_in_pxelinux_cfg_block clonezilla
+  add_runlevel_1_in_grub_efi_cfg_block clonezilla-se-client
 
   # If the mode is in always_restore, and PXE default menu is assigned to local (-y0), we will set local boot as default. Since the always_restore mode is only useful with local OS exists. But if in some scenario, such as production clone flow, maybe pxe_menu_default_mode=clone is useful, since a lot of hardisks will be replaced one by one.
   if [ "$always_restore" = "yes" ]; then
    case "$pxe_menu_default_mode" in
      "local")
          force_pxe_clients_boot_label local "$local_os_menu_label"
+	 # TODO, a better way to replace boot local under this case that
+	 # there is no easy way to boot local in uEFI mode.
          ;;
      "drbl")
          force_pxe_clients_boot_label drbl
+         force_grub_efi_clients_boot_label drbl-client
          ;;
    esac
   fi
@@ -6631,6 +6645,7 @@ prep_client_inittab_rc_srv() {
         remove_opt_in_pxelinux_cfg_block Clonezilla-live ocs_live_run
       else
         remove_opt_in_pxelinux_cfg_block clonezilla ocs_opt
+        remove_opt_in_grub_efi_cfg_block "--id clonezilla-se-client" ocs_opt
       fi
       if [ -d "$drblroot/$node_ip/etc/" ]; then
 	# We can not just mkdir -p $drblroot/$node_ip/etc/ocs/, otherwise it will make DRBL SSI template fail... since if it's created, the etc tarball will just contains one file /etc/ocs/ocs-run.param. We will only test if $drblroot/$node_ip/etc/ exists, if so, it's full drbl/clonezilla mode. we can create the dir $drblroot/$node_ip/etc/ocs/, and put the param.
@@ -6656,6 +6671,7 @@ prep_client_inittab_rc_srv() {
       else
         # For nfsroot's client, we process select_in_client in /etc/rc1.d/s19ocs-run
         add_opt_in_pxelinux_cfg_block clonezilla ocs_opt "-l en_US.UTF-8 $OCS_OPT $rc_task $rc_opt"
+        add_opt_in_grub_efi_cfg_block "--id clonezilla-se-client" ocs_opt "-l en_US.UTF-8 $OCS_OPT $rc_task $rc_opt"
       fi
       ;;
     both)
@@ -6679,6 +6695,7 @@ prep_client_inittab_rc_srv() {
       else
         # For nfsroot's client, we process select_in_client in /etc/rc1.d/s19ocs-run
         add_opt_in_pxelinux_cfg_block clonezilla ocs_opt "-l en_US.UTF-8 $OCS_OPT $rc_task $rc_opt"
+        add_opt_in_grub_efi_cfg_block "--id clonezilla-se-client" ocs_opt "-l en_US.UTF-8 $OCS_OPT $rc_task $rc_opt"
       fi
       ;;
     *)
@@ -8033,8 +8050,15 @@ task_restoreparts() {
       if `is_gpt_partitition_table_disk /dev/$ihd`; then
         echo "Running: update-efi-nvram-boot-entry -r $target_dir_fullpath/efi-nvram.dat /dev/$ihd" | tee --append $OCS_LOGFILE
         update-efi-nvram-boot-entry -r $target_dir_fullpath/efi-nvram.dat /dev/$ihd | tee --append $OCS_LOGFILE
-	# After EFI NVRAM is updated, the boot loader of network boot might be shift. We have to move it back if the BootCurrent is network boot.
-	set-netboot-1st-efi-nvram -b
+        if [ "$efi_netboot_1st_in_nvram" = "yes" ]; then
+          # "efi_netboot_1st_in_nvram" is from drbl-ocs.conf.
+          is_spawned_by_drbl_ocs $ocs_ppid
+          rc=$?
+          if [ "$rc" -eq 0 ]; then
+	    # After EFI NVRAM is updated, the boot loader of network boot might be shifted. We have to move it back if the BootCurrent is network boot.
+	    set-netboot-1st-efi-nvram -b
+          fi
+        fi
       fi
     done
   fi
@@ -8365,9 +8389,11 @@ do_select_in_client() {
     force_pxe_clients_boot_label Clonezilla-live "$clonezilla_client_menu_label_prefix: choose save or restore later"
   else
     force_pxe_clients_boot_label clonezilla "$clonezilla_client_menu_label_prefix: choose save or restore later"
+    force_grub_efi_clients_boot_label "clonezilla-se-client" "$clonezilla_client_menu_label_prefix: choose save or restore later"
   fi
   # set runlevel 1 to kernel parameter in pxelinux config
   add_runlevel_1_in_pxelinux_cfg_block clonezilla
+  add_runlevel_1_in_grub_efi_cfg_block clonezilla-se-client
   # Set the single user mode password if not setting for client...This will be safer..."
   set_clients_rc1_passwd $IP_LIST
 
@@ -8382,6 +8408,7 @@ do_select_in_client() {
          ;;
      "drbl")
          force_pxe_clients_boot_label drbl
+         force_grub_efi_clients_boot_label drbl-client
          ;;
    esac
   fi
@@ -11085,3 +11112,115 @@ is_cloudfuse_ocsroot() {
   fi
   return $rc
 } # end of is_cloudfuse_ocsroot
+#
+add_opt_in_grub_efi_cfg_block() {
+  # add something like: ocs_opt="--language 0  -g auto -p true restoredisk 2disks hda hdb" in grub efi nb config file
+  local entry_id="$1" # e.g. "--id clonezilla-se-client"
+  local opt_name="$2" # can be ocs_opt (for NFSRoot-based Clonezilla client) or ocs_live_run (for Clonezilla-live-based client)
+  local opt_content="$3"
+  local tag_found
+  local sub_menu_entry_cmd
+  [ -z "$entry_id" ] && echo "No entry_id in add_opt_in_grub_efi_cfg_block!" && exit 1
+  [ -z "$opt_name" ] && echo "opt_name NOT specified in add_opt_in_grub_efi_cfg_block! Abort!" && exit 1
+  [ -z "$opt_content" ] && echo "opt_content NOT specified in add_opt_in_grub_efi_cfg_block! Abort!" && exit 1
+  lines="$(get_grub_efi_image_block "$entry_id" $GRUB_CONF)"
+  begin_line="$(echo $lines | awk -F" " '{print $1}')"
+  end_line="$(echo $lines | awk -F" " '{print $2}')"
+  if [ -z "$begin_line" -o -z "$end_line" ]; then
+    echo "No \"$entry_id\" found in $GRUB_CONF, skip adding that."
+    return 1
+  fi
+  tag_found="$(LC_ALL=C head -n $end_line $GRUB_CONF | tail -n $(($end_line-$begin_line)) | grep -Eiw "^[[:space:]]*linux[[:space:]]*.*[[:space:]]+$opt_name=.*([[:space:]]+|$)")"
+  if [ -z "$tag_found" ]; then
+    # append ocs_opt=... in the end of linux kernel parameter.
+    sub_menu_entry_cmd="if ($begin_line..$end_line) {s|(^[[:space:]]*linux[[:space:]]+.*)|\$1 $opt_name=\\\\\"$opt_content\\\\\"|i}"
+    LC_ALL=C perl -pi -e "$sub_menu_entry_cmd" $GRUB_CONF
+  else
+    # overwrite existing ocs_opt=...
+    # ocs_opt must be the last parameters in default append for grub efi nb.
+    # If tag if found, 2 cases: (1) with "" (e.g. ocs_daemonon="ssh", (2) without "" (e.g. ocs_daemonon=ssh)
+    if [ -n "$(echo $tag_found | grep -iE "$opt_name=\\\\\"[^\"]*\\\\\"")" ]; then
+      sub_menu_entry_cmd="if ($begin_line..$end_line) {s|(^[[:space:]]*linux[[:space:]]*.*)[[:space:]]+$opt_name=\"[^\"]*\"([[:space:]]+.*$)|\$1 $opt_name=\\\\\"$opt_content\\\\\"\$2|i}"
+    else
+      sub_menu_entry_cmd="if ($begin_line..$end_line) {s|(^[[:space:]]*linux[[:space:]]*.*)[[:space:]]+$opt_name=[^[:space:]]+([[:space:]]+.*$)|\$1 $opt_name=\\\\\"$opt_content\\\\\"\$2|i}"
+    fi
+    LC_ALL=C perl -pi -e "$sub_menu_entry_cmd" $GRUB_CONF
+  fi
+} # end of add_opt_in_grub_efi_cfg_block
+#
+remove_opt_in_grub_efi_cfg_block() {
+  local entry_id="$1" # e.g. "--id clonezilla-se-client"
+  local opt_name="$2" # can be ocs_opt (for NFSRoot-based Clonezilla client) or ocs_live_run (for Clonezilla-live-based client)
+  local tag_found
+  local sub_menu_entry_cmd
+  [ -z "$entry_id" ] && echo "No entry_id in remove_opt_in_pxelinux_cfg_block!" && exit 1
+  # remove something like ocs_opt=... from the append .... like this in pxelinux config:
+  # append ... ocs_opt="--language 0  -g auto -p true restoredisk 2disks hda hdb"...
+  lines="$(get_grub_efi_image_block "$entry_id" $GRUB_CONF)"
+  begin_line="$(echo $lines | awk -F" " '{print $1}')"
+  end_line="$(echo $lines | awk -F" " '{print $2}')"
+  if [ -z "$begin_line" -o -z "$end_line" ]; then
+    echo "No \"$entry_id\" found in $GRUB_CONF, skip removing that."
+    return 1
+  fi
+  # 2 types of boot parameters, 1st one is with "=" (e.g. ocs_opt=...), the 2nd one is without "=" (e.g. quiet). Here first we test if the one with "=" is found or not.
+  tag_found="$(LC_ALL=C head -n $end_line $GRUB_CONF | tail -n $(($end_line-$begin_line)) | grep -Eiw "^[[:space:]]*linux[[:space:]]*.*[[:space:]]+$opt_name=.*([[:space:]]+|$)")"
+  if [ -n "$tag_found" ]; then
+    # 1st type, i.e. with "=". 2 types of them. 
+    # (1) with ", i.e. ocs_live_run="ocs-live-general"
+    # (2) without ", i.e. ocs_live_run=ocs-live-general
+
+    # (1) with ", i.e. ocs_live_run="ocs-live-general"
+    sub_menu_entry_cmd="if ($begin_line..$end_line) {s|(^[[:space:]]*linux[[:space:]]+.*)[[:space:]]+$opt_name=\\\\\"[^\"]*\\\\\"([[:space:]]+.*)|\$1\$2|i}"
+    LC_ALL=C perl -pi -e "$sub_menu_entry_cmd" $GRUB_CONF
+    # (2) without ", i.e. ocs_live_run=ocs-live-general
+    sub_menu_entry_cmd="if ($begin_line..$end_line) {s|(^[[:space:]]*linux[[:space:]]+.*)[[:space:]]+$opt_name=[^[:space:]]+([[:space:]]+.*)|\$1\$2|i}"
+    LC_ALL=C perl -pi -e "$sub_menu_entry_cmd" $GRUB_CONF
+  else
+    # 2nd type, i.e. without "=", or nothing. Even if nothing, perl won't fail. Therefore just run it.
+    sub_menu_entry_cmd="if ($begin_line..$end_line) {s|(^[[:space:]]*linux[[:space:]]+.*)[[:space:]]+$opt_name([[:space:]]+.*)|\$1\$2|i}"
+    LC_ALL=C perl -pi -e "$sub_menu_entry_cmd" $GRUB_CONF
+  fi
+} # end of remove_opt_in_grub_efi_cfg_block()
+#
+force_grub_efi_clients_boot_label() {
+  local entry_id="$1" # e.g. drbl-client, clonezilla-se-client
+  local menu_des="$2" # e.g. "Clonezilla: multicast restore precise-x86 to disk sda"
+  [ -z "$entry_id" ] && echo "No entry_id in force_grub_efi_clients_boot_label!" && exit 1
+  if [ -n "$menu_des" ]; then
+    echo "Setting the GRUB EFI clients to DRBL mode with label \"$menu_des\"..."
+    set-default-grub-efi-img -i "$entry_id" -c $GRUB_CONF -l "$menu_des"
+  else
+    echo "Setting the GRUB EFI clients to DRBL mode, keep orig menu label..."
+    set-default-grub-efi-img -i "$entry_id" -c $GRUB_CONF
+  fi
+  # specify the nodes if assigned by user
+  [ "$LIST_HOST" = "on" ] && set_specific_host_grub_efi_conf $IP_LIST
+} # end of force_grub_efi_clients_boot_label
+#
+add_runlevel_1_in_grub_efi_cfg_block() {
+  local entry_id="$1"
+  local sub_menu_entry_cmd
+  [ -z "$entry_id" ] && echo "No entry_id in add_runlevel_1_in_grub_efi_cfg_block!" && exit 1
+  lines=$(get_grub_efi_image_block "$entry_id" $GRUB_CONF)
+  begin_line=$(echo $lines | awk -F" " '{print $1}')
+  end_line=$(echo $lines | awk -F" " '{print $2}')
+  tag_found="$(head -n $end_line $GRUB_CONF | tail -n $(($end_line-$begin_line)) | grep -Ei "^[[:space:]]*linux[[:space:]]*.*[[:space:]]+\<1\>([[:space:]]+|$)")"
+  if [ -z "$tag_found" ]; then
+    sub_menu_entry_cmd="if ($begin_line..$end_line) {s|(^[[:space:]]*linux[[:space:]]+.*)|\$1 1|i}"
+    LC_ALL=C perl -pi -e "$sub_menu_entry_cmd" $GRUB_CONF
+  fi
+} # end of add_runlevel_1_in_grub_efi_cfg_block
+#
+remove_runlevel_1_in_grub_efi_cfg_block() {
+  local entry_id="$1"
+  local sub_menu_entry_cmd
+  [ -z "$entry_id" ] && echo "No entry_id in remove_runlevel_1_in_grub_efi_cfg_block!" && exit 1
+  # remove 1 from the linux .... like this in GRUB config:
+  # linux vmlinuz-pxe ramdisk_size=12288  devfs=nomount drblthincli=off selinux=0 1
+  lines=$(get_grub_efi_image_block "$entry_id" $GRUB_CONF)
+  begin_line="$(echo $lines | awk -F" " '{print $1}')"
+  end_line="$(echo $lines | awk -F" " '{print $2}')"
+  sub_menu_entry_cmd="if ($begin_line..$end_line) {s|(^[[:space:]]*linux[[:space:]]+.*)[[:space:]]+1([[:space:]]+.*)|\$1\$2|i}"
+  LC_ALL=C perl -pi -e "$sub_menu_entry_cmd" $GRUB_CONF
+} # end of remove_runlevel_1_in_grub_efi_cfg_block()
