When failing to open LUKS dev, dd is an option.
Instead of bailing out in error when failing to open LUKS device,
an option was provided to use dd mode to save LUKS device.
Thanks to Swâmi Petaramesh for suggesting that.
Ref: https://sourceforge.net/p/clonezilla/bugs/402/

diff --git a/scripts/sbin/ocs-functions b/scripts/sbin/ocs-functions
--- a/scripts/sbin/ocs-functions
+++ b/scripts/sbin/ocs-functions
@@ -8987,7 +8987,7 @@ task_saveparts() {
   local target_dir_fullpath clted_normal_devs
   local minix_subpt_start minix_subpt_end minix_subpt_size cmd_save_minix_sub_parts_table
   local pv_on_dsk pv_on_dsk_flag
-  local ask_luks_flag enable_luks_ans 
+  local ask_luks_flag enable_luks_ans ask_luks_passphrase open_luks_again
   local lks_open_cmd clted_luks_devs clted_luks_devs_map_sv lkuuid
   # enable_luks is a global vaariable
 
@@ -9159,7 +9159,6 @@ task_saveparts() {
 
     for id in $clted_luks_devs; do
       lks_dev_map=""
-      save_luks_dev_header $target_dir_fullpath /dev/$id 
       if [ -e "$target_dir_fullpath/luks-crypttab-from-OS.info" ]; then
 	lks_dev_map="$(LC_ALL=C get_luks_mapped_dev_name_from_os /dev/$id from-local-dev $target_dir_fullpath)"
         if [ -z "$lks_dev_map" ]; then
@@ -9178,22 +9177,52 @@ task_saveparts() {
 
       lks_dev_map_basenm="$(basename $lks_dev_map)" # e.g., ocs_luks_vQX
 
-      echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
-      echo "$msg_now_open_luks_dev: /dev/$id" | tee --append $OCS_LOGFILE
-      lks_open_cmd="cryptsetup open --type luks /dev/$id $lks_dev_map_basenm"
-      echo "Running: $lks_open_cmd" | tee --append $OCS_LOGFILE
-      eval $lks_open_cmd
-      rc=$?
-      if [ "$rc" -ne 0 ]; then
-        [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-        echo "Failed to open LUKS device /dev/$id."
-        [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-	exit 1
-      fi
-
-      lkuuid="$(LC_ALL=C ocs-get-dev-info /dev/$id uuid)"
-      echo "/dev/$id $lkuuid $lks_dev_map_basenm" >> $target_dir_fullpath/luks-dev.list
-      clted_luks_devs_map_sv="$clted_luks_devs_map_sv $lks_dev_map_basenm"
+      ask_luks_passphrase="yes"
+      while [ "$ask_luks_passphrase" = "yes" ]; do
+        echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
+        echo "$msg_now_open_luks_dev: /dev/$id" | tee --append $OCS_LOGFILE
+        lks_open_cmd="cryptsetup open --type luks /dev/$id $lks_dev_map_basenm"
+        echo "Running: $lks_open_cmd" | tee --append $OCS_LOGFILE
+        eval $lks_open_cmd
+        rc=$?
+        if [ "$rc" -eq 0 ]; then
+          save_luks_dev_header $target_dir_fullpath /dev/$id 
+          lkuuid="$(LC_ALL=C ocs-get-dev-info /dev/$id uuid)"
+          echo "/dev/$id $lkuuid $lks_dev_map_basenm" >> $target_dir_fullpath/luks-dev.list
+          clted_luks_devs_map_sv="$clted_luks_devs_map_sv $lks_dev_map_basenm"
+          ask_luks_passphrase="no"
+	else
+          ask_luks_flag="yes"
+          while [ "$ask_luks_flag" = "yes" ]; do
+            echo $msg_delimiter_star_line
+            [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+            echo "$msg_failed_to_open_this_luks_dev: /dev/$id."
+            echo "$msg_do_you_want_to_try_to_open_it_again"
+            echo "$msg_if_yes_open_luks_again"
+            echo "$msg_if_no_dd_mode_will_be_used"
+            [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+            echo -n "[y/n] "
+            read open_luks_again
+            case "$open_luks_again" in
+              y|Y|[yY][eE][sS]) ask_luks_passphrase="yes"
+                                ask_luks_flag="no" ;;
+              n|N|[nN][oO])     ask_luks_passphrase="no"
+                                ask_luks_flag="no"
+				# We have to put the /dev/$id to clted_normal_devs, treat it as normal device which dd will be used.
+                                clted_normal_devs="$clted_normal_devs $id"
+				;;
+              *)
+                 [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+                 echo "$msg_you_have_to_enter_yes_or_no!"
+                 [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+                 echo $msg_delimiter_star_line
+                 ask_luks_flag="yes"
+                 ;;
+            esac
+          done
+        fi
+        echo $msg_delimiter_star_line
+      done
     done
     # Skip using save_crypttab_from_os. Normally the crypttab can not be found before LUKS is opened in the OS partition.
     # It should be found in the initramfs. So we use extract_crypttab_from_initramfs.
@@ -9475,7 +9504,7 @@ task_restoreparts() {
   local efi_info_tmp
   local processed_extended_parts grub_cand_parts
   local lsrc_dev bt_cmd_
-  local lks_mapper lksopen_cmd clted_luks_devs_map_rt
+  local lks_mapper lksopen_cmd clted_luks_devs_map_rt ask_luks_passphrase ask_luks_flag
   # create_temp_img_flag, orig_ocsroot, orig_target_dir and all_bt_part_lv are global variables
 
   if [ -z "$target_dir" ]; then
@@ -9711,22 +9740,50 @@ task_restoreparts() {
       fi
 
       if [ -n "$lks_mapper" ]; then
-        echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
-        [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-        echo "$msg_now_open_luks_dev: /dev/$partition" | tee --append $OCS_LOGFILE
-        [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-        lksopen_cmd="cryptsetup open --type luks /dev/$partition $lks_mapper"
-        echo "Running: $lksopen_cmd" | tee --append $OCS_LOGFILE
-        eval $lksopen_cmd
-	rc=$?
-	if [ "$rc" -eq 0 ]; then
-          clted_luks_devs_map_rt="$clted_luks_devs_map_rt $lks_mapper"
-        else
-          [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-          echo "Failed to open LUKS device /dev/$partition."
+        ask_luks_passphrase="yes"
+        while [ "$ask_luks_passphrase" = "yes" ]; do
+          echo $msg_delimiter_star_line | tee --append $OCS_LOGFILE
+          [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+          echo "$msg_now_open_luks_dev: /dev/$partition" | tee --append $OCS_LOGFILE
           [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-	  exit 1
-	fi
+          lksopen_cmd="cryptsetup open --type luks /dev/$partition $lks_mapper"
+          echo "Running: $lksopen_cmd" | tee --append $OCS_LOGFILE
+          eval $lksopen_cmd
+          rc=$?
+          if [ "$rc" -eq 0 ]; then
+            clted_luks_devs_map_rt="$clted_luks_devs_map_rt $lks_mapper"
+            ask_luks_passphrase="no"
+          else
+            ask_luks_flag="yes"
+            while [ "$ask_luks_flag" = "yes" ]; do
+              echo $msg_delimiter_star_line
+              [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+              echo "$msg_failed_to_open_this_luks_dev /dev/$partition."
+              echo "$msg_do_you_want_to_try_to_open_it_again"
+              [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+              echo -n "[y/n] "
+              read open_luks_again
+              case "$open_luks_again" in
+                y|Y|[yY][eE][sS]) ask_luks_passphrase="yes"
+                                  ask_luks_flag="no" ;;
+                n|N|[nN][oO])
+                                  [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+                                  echo "$msg_failed_to_open_this_luks_dev: /dev/$partition."
+                                  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+                                  echo "$msg_program_stop." | tee --append $OCS_LOGFILE
+	                          exit 1 ;;
+                *)
+                   [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+                   echo "$msg_you_have_to_enter_yes_or_no!"
+                   [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+                   echo $msg_delimiter_star_line
+                   ask_luks_flag="yes"
+                   ;;
+              esac
+            done
+	  fi
+          echo $msg_delimiter_star_line
+        done
       else
         [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
         echo "The mapped device name for /dev/$partition was not found in $target_dir_fullpath/luks-dev.list" | tee --append $OCS_LOGFILE
