Update args parsing in run_ntfsreloc_part.

diff --git a/scripts/sbin/ocs-functions b/scripts/sbin/ocs-functions
--- a/scripts/sbin/ocs-functions
+++ b/scripts/sbin/ocs-functions
@@ -10409,34 +10409,33 @@ run_ntfsreloc_part() {
     while [ $# -gt 0 ]; do
       case "$1" in
         -s|--selected-hd)
-           shift
-           if [ -z "$(echo $1 |grep ^-.)" ]; then
-             # skip the -xx option, in case 
-             selected_hd="$1"
              shift
-           fi
-           [ -z "$selected_hd" ] && echo "-s is used, but no selected_hd assigned." && exit 1
-           ;;
+             if [ -z "$(echo $1 |grep ^-.)" ]; then
+               # skip the -xx option, in case 
+               selected_hd="$1"
+               shift
+             fi
+             [ -z "$selected_hd" ] && echo "-s is used, but no selected_hd assigned." && exit 1
+             ;;
         -p|--selected-parts)
-           shift
-           if [ -z "$(echo $1 |grep ^-.)" ]; then
-             # skip the -xx option, in case 
-             selected_parts="$1"
              shift
-           fi
-           if [ -z "$selected_parts" ]; then
-             echo "-p is used, but no selected_parts assigned." | tee --append ${OCS_LOGFILE}
+             if [ -z "$(echo $1 |grep ^-.)" ]; then
+               # skip the -xx option, in case 
+               selected_parts="$1"
+               shift
+             fi
+             if [ -z "$selected_parts" ]; then
+               echo "-p is used, but no selected_parts assigned." | tee --append ${OCS_LOGFILE}
+               echo "$msg_program_stop" | tee --append ${OCS_LOGFILE}
+               [ "$save_restore_error_log" = "yes" ] && copy_error_log
+               exit 1
+             fi
+             ;;
+        -*)  echo "${0}: ${1}: invalid option in run_ntfsreloc_part." | tee --append ${OCS_LOGFILE} >&2
              echo "$msg_program_stop" | tee --append ${OCS_LOGFILE}
              [ "$save_restore_error_log" = "yes" ] && copy_error_log
-             exit 1
-           fi
-           ;;
-        -*)     echo "${0}: ${1}: invalid option" | tee --append ${OCS_LOGFILE} >&2
-                USAGE | tee --append ${OCS_LOGFILE} >& 2
-                echo "$msg_program_stop" | tee --append ${OCS_LOGFILE}
-                [ "$save_restore_error_log" = "yes" ] && copy_error_log
-                exit 2 ;;
-        *)      break ;;
+             exit 2 ;;
+         *)  break ;;
       esac
     done
     ntfs_boot_partition="$1"
