Make cnvt-ocs-dev convert the BT related files.

diff --git a/sbin/cnvt-ocs-dev b/sbin/cnvt-ocs-dev
--- a/sbin/cnvt-ocs-dev
+++ b/sbin/cnvt-ocs-dev
@@ -138,11 +138,17 @@ fi
 # check src_dev
 check_input_hd $src_dev
 if [ -z "$(unalias ls 2>/dev/null; ls $ocsroot/$image_name/$(to_filename ${src_dev})* 2>/dev/null)" ]; then
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-  echo "$ocsroot/$image_name/$(to_filename ${src_dev})* NOT found!"
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-  echo "Program terminated!"
-  exit 1
+  if [ -e "$ocsroot/$image_name/00-pseudo-img-note.txt" ]; then
+    # Do not exit when this is in the client of Clonezilla lite server since the source
+    # device file does not exist in the pseudo image.
+    echo "File $ocsroot/$image_name/00-pseudo-img-note.txt was found. This should be in Clonezilla lite client."
+  else
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+    echo "$ocsroot/$image_name/$(to_filename ${src_dev})* NOT found!"
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+    echo "Program terminated!"
+    exit 1
+  fi
 fi
 
 # check tgt_dev
@@ -235,6 +241,21 @@ filenames_2_be_mod_about_parts="$(LC_ALL=C find $ocsroot/$image_name/ \( -name \
 "$(to_filename ${src_dev})*.*-img*" -o -name "$(to_filename ${src_dev})*.files-*sum.info.gz" -o -name "$(to_filename ${src_dev})*-ebr" \) -print | sort)"
 filenames_2_be_mod_about_swap="$(LC_ALL=C find $ocsroot/$image_name/ -name \
 "swappt-$(to_filename ${src_dev})*.info" -print | sort)"
+# For *.torrent and part dir, e.g., sda1.torrent, sda1
+# files example under $ocsroot/btzone/:
+#  ├── btraw-psdo-20190522-145631
+#  │   ├── 00-pseudo-img-note.txt
+#  │   ├── sda1.torrent
+#  │   ├── sda1.torrent.info
+#  │   └── sda2.torrent
+#  │   └── sda2.torrent.info
+#  └── xenial-x86-20171202-zst
+#      ├── Info-img-id.txt
+#      ├── sda1 (dir)
+#      └── sda1.torrent
+#      └── sda1.torrent.info
+filenames_2_be_mod_about_bt_metadata="$(LC_ALL=C find $ocsroot/btzone/$image_name/ \( -name "$(to_filename ${src_dev})*.torrent*" \) -print | sort)"
+filenames_2_be_mod_about_bt_part_dir="$(LC_ALL=C find $ocsroot/btzone/$image_name/ -type d \( -name "$(to_filename ${src_dev})*" \) -print | sort)"
 
 # Process the disk-related file names
 for im in $filenames_2_be_mod_about_disk; do
@@ -295,6 +316,41 @@ for im in $filenames_2_be_mod_about_swap; do
     exit 1
   fi
   mv -vf $ocsroot/$image_name/$imname $ocsroot/$image_name/$newname
+done
+# For *.torrent and part dir, e.g., sda1.torrent, sda1
+# files example under $ocsroot/btzone/:
+#  ├── btraw-psdo-20190522-145631
+#  │   ├── 00-pseudo-img-note.txt
+#  │   ├── sda1.torrent
+#  │   ├── sda1.torrent.info
+#  │   └── sda2.torrent
+#  │   └── sda2.torrent.info
+#  └── xenial-x86-20171202-zst
+#      ├── Info-img-id.txt
+#      ├── sda1 (dir)
+#      └── sda1.torrent
+#      └── sda1.torrent.info
+for im in $filenames_2_be_mod_about_bt_metadata $filenames_2_be_mod_about_bt_part_dir; do
+  [ ! -e "$im" ] && continue
+  imname="$(LC_ALL=C basename $im)"
+  # [p]? is for cciss device partitions, e.g. when convering cciss/c0d0 to sda
+  # cciss/c0d0p1 -> sda1
+  case $tgt_dev in
+  cciss*|mmcblk*|md*|rd*|ida*|nvme*|nbd*)
+    newname="$(LC_ALL=C echo $imname | sed -r -e "s/$(to_filename ${src_dev})[p]?/$(to_filename ${tgt_dev})p/g")"
+    ;;
+  *)
+    newname="$(LC_ALL=C echo $imname | sed -r -e "s/$(to_filename ${src_dev})[p]?/$(to_filename ${tgt_dev})/g")"
+    ;;
+  esac
+  if [ -z "$newname" ]; then
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+    echo "Name converted failed!"
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+    echo "Program terminated!"
+    exit 1
+  fi
+  mv -vf $ocsroot/btzone/$image_name/$imname $ocsroot/btzone/$image_name/$newname
 done
 
 exit 0
