Use xorriso instead of genisoimage.
Use xorriso instead of genisoimage when creating DRBL/GParted live iso.
With this, no need to patch genisoimage to work with EFI booting, and no
need to run isohybrid for the created iso file.

diff --git a/sbin/create-gparted-live b/sbin/create-gparted-live
--- a/sbin/create-gparted-live
+++ b/sbin/create-gparted-live
@@ -60,8 +60,6 @@ vga_mode_gparted_live="normal"
 run_binary_hook_script="gparted-efi-misc-binary-hook"
 # The option to create a corresponding source image.
 gen_source_tarball="no"
-# Flag to put EFI booting image in iso
-enabled_EFI=""
 
 #
 check_if_root
@@ -295,66 +293,61 @@ create_gparted_live_iso(){
   fi
   # Build the EFI boot image. This is especially for iso file. Not for USB stick.
   efi_img_opt=""
-  if [ "$enabled_EFI" = "true" ]; then
-    # The following codes are referred from Fedora 
-    EFI_BOOTIMG_TMP="$(mktemp -d /tmp/efi-boot.XXXXXX)"
-    EFI_BOOTTREE="$stage1_iso_TMP/EFI"
-    EFI_IMGTREE="$ISOSYSLNX_TMP/EFI/images"
-    EFI_IMG="$EFI_IMGTREE/efiboot.img"
-    mkdir -p $EFI_IMGTREE
-    rm -rf $ISOSYSLNX_TMP/.disk
-    rm -f $EFI_IMG
-    
-    BOOTDISKSIZE="$(LC_ALL=C du -kcs $EFI_BOOTTREE | tail -n1 | awk '{print $1}')"
-    BOOTDISKSIZE="$(LC_ALL=C echo "scale=0; $BOOTDISKSIZE * 1.03 / 1" | bc -l)"
-    echo "The size of the $EFI_IMG is $BOOTDISKSIZE"
-    mkdosfs -n GParted-EFI -C $EFI_IMG $BOOTDISKSIZE >/dev/null
-    mount -o loop,shortname=winnt,umask=0077 -t vfat $EFI_IMG $EFI_BOOTIMG_TMP
-    mkdir -p $EFI_BOOTIMG_TMP/EFI/
-    if [ "$live_efi_boot_loader" = "grub" ]; then
-      # In this case, bootx64.efi is in $EFI_BOOTTREE/, but we should exclude the existing $EFI_BOOTTREE/images/efiboot.img
-      # However, when mkdosfs we do not exclude $EFI_BOOTTREE/images/efiboot.img, so the size might be counted. It's better to put efiboot.img not in /EFI/ in the future.
-      rsync -a --exclude images/ $EFI_BOOTTREE/* $EFI_BOOTIMG_TMP/EFI/
-    elif [ "$live_efi_boot_loader" = "syslinux" ]; then
-      # In this case, bootx64.efi is copied in $ISOSYSLNX_TMP/EFI/, we should do something similar with ocs-gen-grub2-efi-bldr
-      rsync -a --exclude images/ $ISOSYSLNX_TMP/EFI/* $EFI_BOOTIMG_TMP/EFI/
-      # TODO similar to ocs-gen-grub2-efi-bldr, create a syslinux.cfg to include /syslinux/syslinux.cfg.
-    fi
-    umount $EFI_BOOTIMG_TMP
-    if [ -d "$EFI_BOOTIMG_TMP" -a -n \
-    	"$(echo $EFI_BOOTIMG_TMP | grep -e "efi-boot")" ]; then
-      rm -rf $EFI_BOOTIMG_TMP
-    fi
-    
-    # Create an info file for grub2 to autodetect the cd root
-    # Ref: http://www.sysresccd.org/forums/viewtopic.php?f=5&t=4410
-    mkdir $ISOSYSLNX_TMP/.disk
-    echo -n "[GParted]" > $ISOSYSLNX_TMP/.disk/info
-    
-    efi_img_opt="-eltorito-alt-boot -efi-boot EFI/images/efiboot.img -no-emul-boot"
-    # For Ubuntu uEFI secure boot signed grubx64.efi, it will search /boot/grub/grub.cfg instead of what we have (/EFI/boot/grub.cfg). Although we do not use Ubuntu as the underlaying OS, we still keep this for the future just in case.
-    mkdir -p $ISOSYSLNX_TMP/boot/grub/
-    cat <<-EFI_END > $ISOSYSLNX_TMP/boot/grub/grub.cfg
+  # The following codes are referred from Fedora 
+  EFI_BOOTIMG_TMP="$(mktemp -d /tmp/efi-boot.XXXXXX)"
+  EFI_BOOTTREE="$stage1_iso_TMP/EFI"
+  EFI_IMG="$ISOSYSLNX_TMP/boot/grub/efiboot.img"
+  mkdir -p $ISOSYSLNX_TMP/boot/grub/
+  rm -rf $ISOSYSLNX_TMP/.disk
+  rm -f $EFI_IMG
+  
+  BOOTDISKSIZE="$(LC_ALL=C du -kcs $EFI_BOOTTREE/boot/boot*.efi | tail -n1 | awk '{print $1}')"
+  BOOTDISKSIZE="$(LC_ALL=C echo "scale=0; $BOOTDISKSIZE * 1.02 / 1" | bc -l)"
+  echo "The size of the $EFI_IMG is $BOOTDISKSIZE"
+  mkdosfs -n GParted-EFI -C $EFI_IMG $BOOTDISKSIZE >/dev/null
+  mount -o loop,shortname=winnt,umask=0077 -t vfat $EFI_IMG $EFI_BOOTIMG_TMP
+  mkdir -p $EFI_BOOTIMG_TMP/EFI/boot/
+  if [ "$live_efi_boot_loader" = "grub" ]; then
+    # In this case, bootx64.efi is in $EFI_BOOTTREE/
+    rsync -a $EFI_BOOTTREE/boot/boot*.efi $EFI_BOOTIMG_TMP/EFI/boot/
+  elif [ "$live_efi_boot_loader" = "syslinux" ]; then
+    # In this case, bootx64.efi is copied in $ISOSYSLNX_TMP/EFI/, we should do something similar with ocs-gen-grub2-efi-bldr
+    rsync -a $ISOSYSLNX_TMP/EFI/boot*.efi $EFI_BOOTIMG_TMP/EFI/boot/
+    # TODO similar to ocs-gen-grub2-efi-bldr, create a syslinux.cfg to include /syslinux/syslinux.cfg.
+  fi
+  umount $EFI_BOOTIMG_TMP
+  if [ -d "$EFI_BOOTIMG_TMP" -a -n \
+  	"$(echo $EFI_BOOTIMG_TMP | grep -e "efi-boot")" ]; then
+    rm -rf $EFI_BOOTIMG_TMP
+  fi
+  
+  # Create an info file for grub2 to autodetect the cd root
+  # Ref: http://www.sysresccd.org/forums/viewtopic.php?f=5&t=4410
+  mkdir $ISOSYSLNX_TMP/.disk
+  echo -n "[GParted]" > $ISOSYSLNX_TMP/.disk/info
+  
+  cat <<-EFI_END > $ISOSYSLNX_TMP/boot/grub/grub.cfg
 # This file is for compatibility to Ubuntu Linux's uEFI secure boot. 
 # The real config file for grub is /EFI/boot/grub.cfg.
 configfile /EFI/boot/grub.cfg
 EFI_END
-    efi_img_graft_opt="/.disk/=$ISOSYSLNX_TMP/.disk"
-  fi
+  efi_img_graft_opt="/.disk/=$ISOSYSLNX_TMP/.disk"
 
-  # Prepare the sort file for genisoimage.
+  # Prepare the sort file for xorriso.
   gen_iso_sort_file $ISOSYSLNX_TMP/syslinux/iso_sort.txt
 
   # Create the iso file
-  genisoimage \
+  xorriso \
+   -as mkisofs -R -r -J -joliet-long -l -cache-inodes -iso-level 3 \
+   -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin -partition_offset 16 \
    -A "GParted Live CD" \
-   -V "GParted-live" \
    -publisher "GParted http://gparted.org" \
-   -f -r -hide-rr-moved -hide-joliet-trans-tbl -J -l -allow-limited-size\
+   -V "GParted-live" \
    -b syslinux/isolinux.bin -c syslinux/boot.cat \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
+   -eltorito-alt-boot --efi-boot boot/grub/efiboot.img \
+   -isohybrid-gpt-basdat -isohybrid-apm-hfsplus \
    -sort $ISOSYSLNX_TMP/syslinux/iso_sort.txt \
-   $efi_img_opt \
    $mkiso_exclude_opt \
    -graft-points \
    $sys_files_dir_graft_point \
@@ -459,53 +452,47 @@ create_gparted_live_zip() {
   chmod 755 $USB_TMP/EFI
   find $USB_TMP/EFI -type d -exec chmod 755 {} \;
 
-  if [ "$enabled_EFI" = "true" ]; then
-    # Build the EFI boot image. This is especially for iso file. Not for USB stick. However, here we still prepare the file so that later it's easier to use genisoimage to create the EFI-enabled iso.
-    # The following codes are referred from Fedora 
-    EFI_BOOTIMG_TMP="$(mktemp -d /tmp/efi-boot.XXXXXX)"
-    EFI_BOOTTREE="$stage1_iso_TMP/EFI"
-    EFI_IMGTREE="$USB_TMP/EFI/images"
-    EFI_IMG="$EFI_IMGTREE/efiboot.img"
-    mkdir -p $EFI_IMGTREE
-    rm -rf $USB_TMP/.disk
-    rm -f $EFI_IMG
-    
-    BOOTDISKSIZE="$(LC_ALL=C du -kcs $EFI_BOOTTREE | tail -n1 | awk '{print $1}')"
-    BOOTDISKSIZE="$(LC_ALL=C expr $BOOTDISKSIZE + 100)"
-    echo "The size of the $EFI_IMG is $BOOTDISKSIZE"
-    mkdosfs -n GParted-EFI -C $EFI_IMG $BOOTDISKSIZE >/dev/null
-    mount -o loop,shortname=winnt,umask=0077 -t vfat $EFI_IMG $EFI_BOOTIMG_TMP
-    mkdir -p $EFI_BOOTIMG_TMP/EFI/
-    if [ "$live_efi_boot_loader" = "grub" ]; then
-      # In this case, bootx64.efi is in $EFI_BOOTTREE/, but we should exclude the existing $EFI_BOOTTREE/images/efiboot.img
-      # However, when mkdosfs we do not exclude $EFI_BOOTTREE/images/efiboot.img, so the size might be counted. It's better to put efiboot.img not in /EFI/ in the future.
-      rsync -a --exclude images/ $EFI_BOOTTREE/* $EFI_BOOTIMG_TMP/EFI/
-    elif [ "$live_efi_boot_loader" = "syslinux" ]; then
-      # In this case, bootx64.efi is copied in $USB_TMP/EFI/, we should do something similar with ocs-gen-grub2-efi-bldr
-      rsync -a --exclude images/ $USB_TMP/EFI/* $EFI_BOOTIMG_TMP/EFI/
-      # TODO similar to ocs-gen-grub2-efi-bldr, create a syslinux.cfg to include /syslinux/syslinux.cfg.
-    fi
-    umount $EFI_BOOTIMG_TMP
-    if [ -d "$EFI_BOOTIMG_TMP" -a -n \
-    	"$(echo $EFI_BOOTIMG_TMP | grep -e "efi-boot")" ]; then
-      rm -rf $EFI_BOOTIMG_TMP
-    fi
-    
-    # Create an info file for grub2 to autodetect the cd root
-    # Ref: http://www.sysresccd.org/forums/viewtopic.php?f=5&t=4410
-    mkdir $USB_TMP/.disk
-    echo -n "[GParted]" > $USB_TMP/.disk/info
+  # Build the EFI boot image. This is especially for iso file. Not for USB stick. However, here we still prepare the file so that later it's easier to use xorriso to create the EFI-enabled iso.
+  # The following codes are referred from Fedora 
+  EFI_BOOTIMG_TMP="$(mktemp -d /tmp/efi-boot.XXXXXX)"
+  EFI_BOOTTREE="$stage1_iso_TMP/EFI"
+  EFI_IMG="$USB_TMP/boot/grub/efiboot.img"
+  mkdir -p $USB_TMP/boot/grub/
+  rm -rf $USB_TMP/.disk
+  rm -f $EFI_IMG
   
-    # For Ubuntu uEFI secure boot signed grubx64.efi, it will search /boot/grub/grub.cfg instead of what we have (/EFI/boot/grub.cfg). Although we do not use Ubuntu as the underlaying OS, we still keep this for the future just in case.
-    mkdir -p $USB_TMP/boot/grub/
-    cat <<-EFI_END > $USB_TMP/boot/grub/grub.cfg
+  BOOTDISKSIZE="$(LC_ALL=C du -kcs $EFI_BOOTTREE/boot/boot*.efi | tail -n1 | awk '{print $1}')"
+  BOOTDISKSIZE="$(LC_ALL=C echo "scale=0; $BOOTDISKSIZE * 1.02 / 1" | bc -l)"
+  echo "The size of the $EFI_IMG is $BOOTDISKSIZE"
+  mkdosfs -n GParted-EFI -C $EFI_IMG $BOOTDISKSIZE >/dev/null
+  mount -o loop,shortname=winnt,umask=0077 -t vfat $EFI_IMG $EFI_BOOTIMG_TMP
+  mkdir -p $EFI_BOOTIMG_TMP/EFI/boot/
+  if [ "$live_efi_boot_loader" = "grub" ]; then
+    # In this case, bootx64.efi is in $EFI_BOOTTREE/
+    rsync -a $EFI_BOOTTREE/boot/boot*.efi $EFI_BOOTIMG_TMP/EFI/boot/
+  elif [ "$live_efi_boot_loader" = "syslinux" ]; then
+    # In this case, bootx64.efi is copied in $USB_TMP/EFI/, we should do something similar with ocs-gen-grub2-efi-bldr
+    rsync -a $USB_TMP/boot/boot*.efi $EFI_BOOTIMG_TMP/EFI/boot/
+    # TODO similar to ocs-gen-grub2-efi-bldr, create a syslinux.cfg to include /syslinux/syslinux.cfg.
+  fi
+  umount $EFI_BOOTIMG_TMP
+  if [ -d "$EFI_BOOTIMG_TMP" -a -n \
+  	"$(echo $EFI_BOOTIMG_TMP | grep -e "efi-boot")" ]; then
+    rm -rf $EFI_BOOTIMG_TMP
+  fi
+  
+  # Create an info file for grub2 to autodetect the cd root
+  # Ref: http://www.sysresccd.org/forums/viewtopic.php?f=5&t=4410
+  mkdir $USB_TMP/.disk
+  echo -n "[GParted]" > $USB_TMP/.disk/info
+  
+  cat <<-EFI_END > $USB_TMP/boot/grub/grub.cfg
 # This file is for compatibility to Ubuntu Linux's uEFI secure boot. 
 # The real config file for grub is /EFI/boot/grub.cfg.
 configfile /EFI/boot/grub.cfg
 EFI_END
-  fi
 
-  # Prepare the sort file for genisoimage. Although we do not use genisoimage here, however, we'd like the file created by ocs-live-dev is the same with that of ocs-iso. So it's easier to convert zip file to iso file.
+  # Prepare the sort file for xorriso. Although we do not use xorriso here, however, we'd like the file created by ocs-live-dev is the same with that of ocs-iso. So it's easier to convert zip file to iso file.
   # Therefore we still put the file iso_sort.txt here.
   gen_iso_sort_file $USB_TMP/syslinux/iso_sort.txt
 
@@ -1066,21 +1053,11 @@ mount -o loop $stage1_target_iso $stage1_iso_TMP
 # Check if EFI boot could be supported.
 if [ ! -e "$stage1_iso_TMP/EFI/boot/bootx64.efi" ]; then
   # We only check bootx64.efi since bootx86.efi is optional.
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-  echo "Warning! /EFI/boot/bootx64.efi was not found in stage1 GParted live!"
-  echo "The generated $target_iso will not support EFI boot!"
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+  echo "/EFI/boot/bootx64.efi was not found in template Clonezilla live!"
   [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-  sleep 5
-  enabled_EFI="false"
-elif [ -n "$(LC_ALL=C genisoimage --help 2>&1 | grep -E -- "-efi-boot")" ]; then
-  # Check if genisoimage support -efi-boot option
-  enabled_EFI="true"
-else
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-  echo "Warning! Setting EFI boot image name is not supported in genisoimage!"
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-  sleep 5
-  enabled_EFI="false"
+  echo "$msg_program_stop"
+  exit 1
 fi
   
 #
@@ -1100,14 +1077,6 @@ umount $stage1_iso_TMP &>/dev/null
 
 # Isohybrid the generated iso file.
 # //NOTE// This is for GParted live iso. It's different from that for template iso.
-
-if [ -e "$real_target_iso" ]; then
-  if type isohybrid &>/dev/null; then
-    echo -n "Isohybriding $real_target_iso... "
-    isohybrid --uefi $real_target_iso
-    echo "done!"
-  fi
-fi
 
 case "$target_media_file" in
   cd|CD|iso|ISO)
