Check partclone_create_torrent.py.
Add a mechanism to check partclone_create_torrent.py in
ocs-gen-bt-metainfo.

diff --git a/sbin/ocs-gen-bt-metainfo b/sbin/ocs-gen-bt-metainfo
--- a/sbin/ocs-gen-bt-metainfo
+++ b/sbin/ocs-gen-bt-metainfo
@@ -200,6 +200,14 @@ ask_and_load_lang_set
 # check DIA
 check_DIA_set_ESC $DIA
 
+if ! type partclone_create_torrent.py &>/dev/null; then
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+  echo "Program partclone_create_torrent.py is required. Install package ezio."
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+  echo "$msg_program_stop!"
+  my_ocs_exit 1
+fi
+
 if [ -z "$output_dir" ]; then
   output_dir="$(pwd)"
 else
