Implemented LUKS2 Repository support.

diff --git a/sbin/ocs-live-repository b/sbin/ocs-live-repository
--- a/sbin/ocs-live-repository
+++ b/sbin/ocs-live-repository
@@ -109,13 +109,42 @@ get_ocsroot_src_from_ocs_repository_if_assigned() {
 }
 #
 do_uri_mount_local_dev() {
-  local rc
+  local rc resolved_part tag val canonical_part
   target_part="$(drbl-uriparse "$ocs_repository" path)"
   # If it's LABEL=<label>, UUID=<uuid>, PARTLABEL=<label>, PARTUUID=<uuid>    
   # The input format is like: ocs_repository="dev:///UUID=XYZ"
   # we have to remove the leading "/"
   target_part="$(echo $target_part | sed -r -e "s@^/(LABEL|UUID|PARTLABEL|PARTUUID|OCS_LIVE_USB)@\1@")"
   # TODO: Browse
+
+  resolved_part="$target_part"
+  if [[ "$target_part" =~ ^(UUID|LABEL|PARTUUID|PARTLABEL)= ]]; then
+    tag="${BASH_REMATCH[1]}"
+    val="${target_part#*=}"
+    case "$(echo "$tag" | tr '[:upper:]' '[:lower:]')" in
+      uuid)      resolved_part="/dev/disk/by-uuid/$val" ;;
+      label)     resolved_part="/dev/disk/by-label/$val" ;;
+      partuuid)  resolved_part="/dev/disk/by-partuuid/$val" ;;
+      partlabel) resolved_part="/dev/disk/by-partlabel/$val" ;;
+    esac
+  fi
+  canonical_part="$(readlink -f "$resolved_part")"
+
+  if [ -b "$canonical_part" ] && cryptsetup isLuks "$canonical_part" &>/dev/null; then
+    echo "LUKS/LUKS2 device detected: $canonical_part"
+    echo "Opening LUKS partition..."
+    cryptsetup close ocs_reporoot_luks &>/dev/null
+    cryptsetup luksOpen "$canonical_part" ocs_reporoot_luks
+    if [ $? -eq 0 ]; then
+      target_part="/dev/mapper/ocs_reporoot_luks"
+    else
+      [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+      echo "Failed to unlock LUKS partition $canonical_part!"
+      [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+      exit 1
+    fi
+  fi
+
   prepare_mnt_point_ocsroot
   case $target_part in
     OCS_LIVE_USB)
diff --git a/sbin/ocs-prep-repo b/sbin/ocs-prep-repo
--- a/sbin/ocs-prep-repo
+++ b/sbin/ocs-prep-repo
@@ -169,6 +169,53 @@ do_mount_local_dev() {
            done
            [ "$chk_ocsroot_mountpont" = "yes" ] && check_if_ocsroot_a_mountpoint
 	   ;;
+     crypto_LUKS|crypto_luks|luks|LUKS|luks2|LUKS2)
+           ask_="true"
+           while [ "$ask_" = "true" ]; do
+             [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+             echo "Opening LUKS partition /dev/$target_part..."
+             [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+             cryptsetup close ocs_reporoot_luks &>/dev/null
+             cryptsetup luksOpen /dev/$target_part ocs_reporoot_luks
+             rc=$?
+             if [ "$rc" -eq 0 ]; then
+               mapped_part_fs="$(LANG=C ocs-get-dev-info /dev/mapper/ocs_reporoot_luks filesystem)"
+               echo "Decrypted filesystem inside /dev/mapper/ocs_reporoot_luks: $mapped_part_fs"
+               case "$mapped_part_fs" in
+                 ntfs)
+                   ntfs-3g /dev/mapper/ocs_reporoot_luks $ocsroot -o $ocsroot_def_mnt_opt
+                   rc=$?
+                   ;;
+                 hfsplus)
+                   LC_ALL=C mount -t hfsplus -o force,$ocsroot_def_mnt_opt /dev/mapper/ocs_reporoot_luks $ocsroot
+                   rc=$?
+                   ;;
+                 *)
+                   LC_ALL=C mount -t auto -o $ocsroot_def_mnt_opt /dev/mapper/ocs_reporoot_luks $ocsroot
+                   rc=$?
+                   ;;
+               esac
+             fi
+             if [ "$rc" -ne 0 ]; then
+               echo $msg_delimiter_star_line
+               [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+               echo "$msg_unable_to_mnt_ocsroot. $msg_do_u_want_to_do_it_again"
+               [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+               echo -n "[Y/n] "
+               read run_again_ans
+               case "$run_again_ans" in
+                 n|N|[nN][oO]) ask_="false" ;;
+                            *) ask_="true" 
+                               umount $ocsroot 2>/dev/null
+                               cryptsetup close ocs_reporoot_luks 2>/dev/null
+                               ;;
+               esac
+             else
+               ask_="false"
+             fi
+           done
+           [ "$chk_ocsroot_mountpont" = "yes" ] && check_if_ocsroot_a_mountpoint
+           ;;
      hfsplus) 
            [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
            echo "$msg_warning_mount_hfsplus_writable"
