ocs-live-final-action.

diff --git a/sbin/ocs-langkbdconf-bterm b/sbin/ocs-langkbdconf-bterm
--- a/sbin/ocs-langkbdconf-bterm
+++ b/sbin/ocs-langkbdconf-bterm
@@ -10,6 +10,33 @@ DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"
 . /etc/drbl/drbl-ocs.conf
 . $DRBL_SCRIPT_PATH/sbin/ocs-functions
 
+# Functions
+USAGE() {
+    echo "$ocs - Program to setup locales and keyboard layout in Clonezilla live"
+    echo "Usage:"
+    echo "To run $ocs:"
+    echo "$ocs"
+    echo "Ex:"
+    echo "To setup locales and keyboard layout in Clonezilla live, run:"
+    echo "   $ocs"
+} # end of USAGE
+
+####################
+### Main program ###
+####################
+
+ocs=`basename $0`
+#
+check_if_root
+#
+while [ $# -gt 0 ]; do
+ case "$1" in
+   -*)     echo "${0}: ${1}: invalid option" >&2
+           USAGE >& 2
+           exit 2 ;;
+   *)      break ;;
+ esac
+done
 
 #
 get_fb_term
