Continue only when mounting repository succeeds.
If failing to mount image repository by ocs-live-repository, do not
continue in ocs-live-run-menu.

diff --git a/sbin/ocs-live-run-menu b/sbin/ocs-live-run-menu
--- a/sbin/ocs-live-run-menu
+++ b/sbin/ocs-live-run-menu
@@ -85,7 +85,15 @@ ocs-live-prerun
 ocs-live-preload
 
 # Prepare image repository if ocs_repository is assigned.
+rc=""
 ocs-live-repository
+rc=$?
+if [ "$rc" -eq 1 ]; then
+  # Only when ocs-live-repository fails to mount repository in ocs-live-repository,
+  # this program will exit. If ocs_repositry is not assigned in /proc/cmdline,
+  # the exit code of ocs-live-repository is 9, not 1. This program will continue.
+  exit 1
+fi
 
 #
 if [ "$use_fb_term" = "yes" ];then
