- Option "-h" was added to ocs-put-signed-grub2-efi-bldr and ocs-gen-grub2-efi-bldr.

diff --git a/sbin/ocs-gen-grub2-efi-bldr b/sbin/ocs-gen-grub2-efi-bldr
--- a/sbin/ocs-gen-grub2-efi-bldr
+++ b/sbin/ocs-gen-grub2-efi-bldr
@@ -15,16 +15,27 @@ grub_required_files="/usr/share/grub/unicode.pf2"
 # Functions
 USAGE() {
   echo "To create an EFI boot loader from grub2."
-  echo "Usage: $0 OUTPUT_DIR"
+  echo "Usage: $ocs OUTPUT_DIR"
   echo "OUTPUT_DIR is the where the created boot loader will be placed."
-  echo "   E.g.  $0 /tmp/efi/"
-}
+  echo "   E.g.  $ocs /tmp/efi/"
+} # end of USAGE
 #
 #############
 ###  MAIN ###
 #############
 #
+ocs=`basename $0`
 check_if_root
+
+#
+while [ $# -gt 0 ]; do
+ case "$1" in
+   -*)     echo "${0}: ${1}: invalid option" >&2
+           USAGE >& 2
+           exit 2 ;;
+   *)      break ;;
+ esac
+done
 
 output_dir="$1"
 
