Now asking use-existing-dhcpd, start-new-dhcpd.
Instead of asking "to-upstream" or "in-isolation", now asking
use-existing-dhcpd, start-new-dhcpd, auto-dhcpd in ocs-live-feed-img.
Support replaying the DHCP service to existing DHCP service.

diff --git a/sbin/ocs-live-feed-img b/sbin/ocs-live-feed-img
--- a/sbin/ocs-live-feed-img
+++ b/sbin/ocs-live-feed-img
@@ -58,8 +58,8 @@ USAGE() {
     echo " -n, --no-nfs-restart     Do not to restart nfs when start or stop $ocs (This is default)"
     echo " -f, --nfs-restart        Restart nfs when start or stop $ocs (Default is to restart nfs)"
     echo " --mcast-iface  PORT      Specify the multicast seed ethernet port PORT (eth0, eth1, eth2...). Suppose clonezilla will try to find that for you, but in some case, you might want to specify that."
-    echo " -x, --full-duplex         Use full-duplex network with udpcast in multicast mode (faster, but does not work with network hub, only works in switch.)."
-    echo " -nm, --netenv-mode         Assign the network environment: to-upstream, in-isolation"
+    echo " -x, --full-duplex        Use full-duplex network with udpcast in multicast mode (faster, but does not work with network hub, only works in switch.)."
+    echo " -dm, --dhcpd-mode        Assign the dhcp service mode: use-existing-dhcpd, start-new-dhcpd, auto-dhcpd, no-dhcpd"
     echo " -md, --massive-deploy-mode Assign the mass deployment mode: broadcast, multicast, or bittorrent"
     echo
     echo "MODE is \"start\" or \"stop\""
@@ -89,8 +89,8 @@ ask_start_or_stop_mode() {
   $DIA --backtitle "$msg_nchc_free_software_labs" --title  \
   "Clonezilla live Lite server" --menu "$msg_ocs_live_lite_server_des\n$msg_choose_mode:" \
   0 0 0 $DIA_ESC \
-  "start"  "$msg_clonezilla_start" \
-  "stop"   "$msg_clonezilla_stop" \
+  "start"  "$msg_start_clonezilla_live_lite_server" \
+  "stop"   "$msg_stop_clonezilla_live_lite_server" \
   "exit"   "$msg_exit. $msg_enter_cml" \
   2> $TMP
   mode="$(cat $TMP)"
@@ -395,7 +395,7 @@ parse_ocs_live_feed_img_cmd_options_with_dash() {
 	    # OCS_OPT is for ocs-sr, not for ocs-live-feed-img
   	    # XXXXXX OCS_OPT="$OCS_OPT -md $massive_deploy_mode"
   	    ;;
-      -nm|--netenv-mode)
+      -dm|--dhcpd-mode)
             shift; n_shift=$((n_shift+1))
             # skip the -xx option, in case 
             if [ -z "$(echo $1 |grep ^-.)" ]; then
@@ -405,7 +405,7 @@ parse_ocs_live_feed_img_cmd_options_with_dash() {
             [ -z "$ocs_litesrv_mode" ] && USAGE && exit 1
 	    # //NOTE// Do not pass -md option to OCS_OPT here.
 	    # OCS_OPT is for ocs-sr, not for ocs-live-feed-img
-  	    # XXXXXX OCS_OPT="$OCS_OPT -nm $ocs_litesrv_mode"
+  	    # XXXXXX OCS_OPT="$OCS_OPT -dm $ocs_litesrv_mode"
   	    ;;
       -*)   echo "${0}: ${1}: invalid option" >&2
             USAGE >& 2
@@ -454,26 +454,14 @@ gen_ocs_live_netboot_conf() {
   grub_menu_to_reveal="clonezilla-live-client local-disk"
   generate-pxe-menu
   gen-grub-efi-nb-menu
-  # Add Clonezilla live
-  if [ -n "$LIVE_MEDIA" -a -d "$LIVE_MEDIA" ]; then
-    # Check the file permission mode
-    squashfs_fmode="$(LC_ALL=C stat -c %a $LIVE_MEDIA/live/filesystem.squashfs | cut -c 3)"
-    if [ "$squashfs_fmode" -ge 4 ]; then
-      # Use link since it's readable for www-data account (default user for lighttpd)
-      drbl-sl -e -b -n -p $LIVE_MEDIA
-    else
-      # Just copy the file to tftpboot root since it's not readable by www-data
-      drbl-sl -b -n -p $LIVE_MEDIA
-      chmod 644 $pxecfg_pd/Clonezilla-live-filesystem.squashfs
-    fi
+  # Add Clonezilla live in the boot menu and for netboot. Actually we will use http service instead of tftpd. However, just run drbl-sl to make things easier. Hence both files for netboot using tftpd and httpd will be ready.
+  if [ "$squashfs_fmode" -ge 4 ]; then
+    # Use link since it's readable for www-data account (default user for lighttpd)
+    drbl-sl -e -b -n -p $LIVE_MEDIA
   else
-    [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-    echo "Failed to find root file system in $LIVE_MEDIA!"
-    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-    echo "Unable to let PXE client boot Clonezilla live."
-    echo -n "$msg_press_enter_to_continue..."
-    read
-    return 1
+    # Just copy the file to tftpboot root since it's not readable by www-data
+    drbl-sl -b -n -p $LIVE_MEDIA
+    chmod 644 $pxecfg_pd/Clonezilla-live-filesystem.squashfs
   fi
   # Reveal and hide boot menu
   for imenu in $pxe_menu_to_reveal; do
@@ -580,7 +568,7 @@ stop_nat_service() {
 } # end of stop_nat_service
 #
 task_start_feed_img_for_cast() {
-  local MCAST_TMP ans_ cast_dev_action
+  local MCAST_TMP ans_ cast_dev_action ocs_litesrv_mode
   local start_cmd
   local OCS_OPT_PRE ocs_opt_dia
   local rc_chkimg
@@ -590,27 +578,67 @@ task_start_feed_img_for_cast() {
   # If network setting is not configured. Ask
   # TODO: What if multiple IP addresses?
   configured_ip="$(get-all-nic-ip --all-ip-address)"
-  if [ -z "$ocs_litesrv_mode" ]; then
+  if [ -z "$client_boot_mode" ]; then
     TMP="$(mktemp /tmp/ocslivemode.XXXXXX)"
     trap "[ -f "$TMP" ] && rm -f $TMP" HUP INT QUIT TERM EXIT
     $DIA --backtitle "$msg_nchc_free_software_labs" --title  \
-    "Network environment" --menu "$msg_which_network_senario\n$msg_choose_mode:" \
+    "Client boot mechanism" --menu "$msg_which_mode_for_client_boot\n$msg_choose_mode:" \
     0 0 0 $DIA_ESC \
-    "to-upstream"  "$msg_connect_to_upstream_network" \
-    "in-isolation" "$msg_in_isolated_environment" \
+    "netboot"          "$msg_boot_client_with_network" \
+    "local-boot-media" "$msg_boot_with_local_media" \
+    "both"             "$msg_boot_client_with_network_and_local_media" \
+    2> $TMP
+    client_boot_mode="$(cat $TMP)"
+    echo "client_boot_mode is $client_boot_mode"
+    [ -f "$TMP" ] && rm -f $TMP
+  fi
+  OCS_OPT_PRE="$OCS_OPT_PRE -cbm $client_boot_mode"
+  ask_dhcpd=""
+  case "$client_boot_mode" in
+    "netboot")          ask_dhcpd="yes";;
+    "local-boot-media") ask_dhcpd="no";;
+    "both")             ask_dhcpd="yes";;
+  esac
+  # Ask if starts own dhcpd or using existing dhcpd
+  if [ "$ask_dhcpd" = "yes" ]; then
+    TMP="$(mktemp /tmp/ocslivemode.XXXXXX)"
+    trap "[ -f "$TMP" ] && rm -f $TMP" HUP INT QUIT TERM EXIT
+    $DIA --backtitle "$msg_nchc_free_software_labs" --title  \
+    "DHCP service" --menu "$msg_how_to_run_dhcpd\n$msg_choose_mode:" \
+    0 0 0 $DIA_ESC \
+    "auto-dhcpd"          "$msg_auto_detect_dhcpd" \
+    "use-existing-dhcpd"  "$msg_use_existing_dhcpd" \
+    "start-new-dhcpd"     "$msg_start_new_dhcpd" \
     2> $TMP
     ocs_litesrv_mode="$(cat $TMP)"
     echo "ocs_litesrv_mode is $ocs_litesrv_mode"
     [ -f "$TMP" ] && rm -f $TMP
+  else
+    # ask_dhcpd is "no"
+    ocs_litesrv_mode="no-dhcpd"
   fi
-  OCS_OPT_PRE="$OCS_OPT_PRE -nm $ocs_litesrv_mode"
+  if [ "$ocs_litesrv_mode" = "auto-dhcpd" ]; then
+    # Detect if there is an existing DHCP service in LAN
+    detect_dhcp_srv_in_lan  # Get use_existing_dhcp_srv
+    case "$use_existing_dhcp_srv" in
+      "yes") ocs_litesrv_mode="use-existing-dhcpd";;
+      "no")  ocs_litesrv_mode="start-new-dhcpd";;
+    esac
+  fi
   case "$ocs_litesrv_mode" in
-    "to-upstream") 
-     # Even if it's local repository, we still have to configure network
-     # otherwise the udp-sender won't start.
-     network_config_if_necessary
+    "no-dhcpd")
+       # Even if no dhcpd, like local repository,
+       # we still have to configure network
+       # otherwise the udp-sender won't start.
+       network_config_if_necessary
        ;;
-    "in-isolation")
+    "use-existing-dhcpd")
+       # Even if it's local repository, we still have to configure network
+       # otherwise the udp-sender won't start.
+       network_config_if_necessary
+       gen_dnsmasq_cfg -a $dnsmasq_cfg
+       ;;
+    "start-new-dhcpd") 
        if [ -z "$configured_ip" ]; then
          config_netcard
        fi
@@ -636,7 +664,8 @@ task_start_feed_img_for_cast() {
        echo "In isolation environment. Now start dhcp service..." 
        gen_lite_dhcpd_conf $dnsmasq_cfg
        ;;
-    *) echo "$msg_program_stop" | tee -a ${OCS_LOGFILE}
+    *) echo "Unknown mode for ocs_litesrv_mode: $ocs_litesrv_mode"
+       echo "$msg_program_stop" | tee -a ${OCS_LOGFILE}
        exit 0
        ;;
   esac
@@ -912,8 +941,13 @@ task_start_feed_img_for_cast() {
   if ! systemctl status lighttpd >/dev/null 2>&1; then
     systemctl start lighttpd | tee -a ${OCS_LOGFILE}
   fi
-  # Start the required services and prepare the PXE and uEFI network boot
-  if [ "$ocs_litesrv_mode" = "in-isolation" ]; then
+
+  # Prepare netboot required files and services
+  case "$ocs_litesrv_mode" in
+   "use-existing-dhcpd"|"start-new-dhcpd") 
+    # Check the file permission mode of squashfs, we need that for later use
+    squashfs_fmode="$(LC_ALL=C stat -c %a $LIVE_MEDIA/live/filesystem.squashfs | cut -c 3)"
+    # Not matter if clients use netboot or not, we start the required services and prepare the PXE and uEFI network boot
     service dnsmasq restart
     start_nat_service
     gen_ocs_live_netboot_conf
@@ -927,7 +961,8 @@ task_start_feed_img_for_cast() {
     # Change fetch protocol to http
     add_opt_in_pxelinux_cfg_block -n Clonezilla-live fetch "http://$cast_srv_ip/Clonezilla-live-filesystem.squashfs"
     add_opt_in_grub_efi_cfg_block -n "clonezilla-live-client" fetch "http://$cast_srv_ip/Clonezilla-live-filesystem.squashfs"
-  fi
+   ;;
+  esac
 
   echo $msg_delimiter_star_line
   # Two parts: img-wo-fs.tar.xz and ocs-client-run.conf
@@ -976,8 +1011,8 @@ CLIENT_END
 
   #
   case "$ocs_litesrv_mode" in
-    "to-upstream")  always_restore="yes" ;; # So that ocsmgrd won't update PXE/Grub NB config
-    "in-isolation") always_restore="no" ;;  # So that ocsmgrd will update PXE/Grub NB confi
+    "use-existing-dhcpd"|"start-new-dhcpd") always_restore="no" ;;  # So that ocsmgrd will update PXE/Grub NB confi
+    "no-dhcpd")                             always_restore="yes" ;; # So that ocsmgrd won't update PXE/Grub NB config
   esac
   start_ocsmgrd_daemon
   echo $msg_delimiter_star_line
@@ -995,10 +1030,12 @@ CLIENT_END
   echo $msg_delimiter_star_line
   [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
 
-  if [ "$ocs_litesrv_mode" = "in-isolation" ]; then
+  case "$ocs_litesrv_mode" in
+   "use-existing-dhcpd"|"start-new-dhcpd") 
     echo "$msg_turn_on_client_to_clone" 
     echo "$msg_if_boot_from_locaL_media:"
-  fi
+    ;;
+  esac
   echo "$msg_boot_client_with_same_version_clonezilla_live: $cast_srv_ip" | tee -a ${OCS_LOGFILE}
   echo "$msg_append_parameter_for_unattended_mode: locales=en_US.UTF-8 keyboard-layouts=us ocs_live_run=\"ocs-live-get-img $cast_srv_ip\"" | tee -a ${OCS_LOGFILE}
   [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
@@ -1021,6 +1058,7 @@ task_stop_feed_img_for_cast() {
   clean_stale_node_pxe_cfg
   clean_stale_node_grub_efi_cfg
   service dnsmasq stop
+  service lighttpd stop
   stop_nat_service
   stop_ocs_service -m $ocs no
 } # task_stop_feed_img_for_cast
@@ -1063,6 +1101,16 @@ export TERM="$TERM"
 check_if_root
 check_if_in_clonezilla_live  # get $LIVE_MEDIA
 ask_and_load_lang_set
+
+# Check if we can find LIVE_MEDIA
+if [ -z "$LIVE_MEDIA" -o ! -d "$LIVE_MEDIA" ]; then
+ [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+ echo "Failed to find root file system in $LIVE_MEDIA!"
+ [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+ echo "Unable to let PXE client boot Clonezilla live."
+ echo "$msg_program_stop!"
+ exit 1
+fi
 
 # check DIA
 check_DIA_set_ESC $DIA
