Temporarily disable dislocker-find.
Temporarily disable dislocker-find in ocs-get-part-info.

diff --git a/sbin/ocs-get-part-info b/sbin/ocs-get-part-info
--- a/sbin/ocs-get-part-info
+++ b/sbin/ocs-get-part-info
@@ -463,17 +463,24 @@ get_type_from_lsblk() {
 #
 check_if_bitlocker_fs() {
   local rc_n rc_f
-  if type dislocker-find &>/dev/null; then
-    dislocker-find $part &>/dev/null
-    # //NOTE// Here the return code for dislocker-find is the number of bitlocker partition. Not the true/false.
-    rc_n=$?
-    if [ "$rc_n" -eq 1 ]; then
-      rc_f="bitlocker"
-    else
-      rc_f=""
-    fi
-    echo "$rc_f"
-  fi
+  #if type dislocker-find &>/dev/null; then
+  #  dislocker-find $part &>/dev/null
+  #  # //NOTE// Here the return code for dislocker-find is the number of bitlocker partition. Not the true/false.
+  #  rc_n=$?
+  #  if [ "$rc_n" -eq 1 ]; then
+  #    rc_f="bitlocker"
+  #  else
+  #    rc_f=""
+  #  fi
+  #  echo "$rc_f"
+  #fi
+  # Temporarily disable dislocker-find since:
+  # (1) It's broken in Debian Sid: https://bugs.debian.org/906430
+  # (2) It seems dislocker-find (depeds on libmbedcrypto1 can not deal with
+  #     Linux kernel >= 4.17 on Debian when in early booted status. Waiting for getrandom...
+  #     https://sourceforge.net/p/clonezilla/discussion/Open_discussion/thread/e1264596
+  #     Maybe related to https://bugs.debian.org/897572 and https://bugs.debian.org/897599
+  echo
 } # end of check_if_bitlocker_fs
 #
 check_if_MSR_part() {
