Make Clonezilla no more depending on Partimage.
Deprecate Partimage, i.e. no more depending on Partimage.
Since it's not in the Debian Buster repository.
It's only recommended to install, not a required package now for
Clonezilla.

diff --git a/sbin/ocs-sr b/sbin/ocs-sr
--- a/sbin/ocs-sr
+++ b/sbin/ocs-sr
@@ -615,6 +615,15 @@ parse_ocs_sr_cmd_options_with_dash() {
     *)      break ;;
   esac
  done
+ if [ -z "$USE_NTFSCLONE" -a -z "$FORCE_TO_USE_DD" -a -z "$USE_PARTCLONE" ]; then
+   # In this case, Partimage is used. However, if Partimage is not installed, we have to switch to Partclone.
+   if ! type partimage >/dev/null 2>&1; then
+     [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+     echo "Partimage was not found in this system. Force to use Partclone."
+     [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+     USE_PARTCLONE="yes"
+   fi 
+ fi
 } # end of parse_ocs_sr_cmd_options_with_dash
 #
 save_only_dia_des() {
