- Usage prompt were added in ocs-live-general, ocs-live-save, and ocs-live-restore.

diff --git a/sbin/ocs-live-general b/sbin/ocs-live-general
--- a/sbin/ocs-live-general
+++ b/sbin/ocs-live-general
@@ -13,6 +13,36 @@ DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"
 # load the setting for clonezilla live.
 [ -e /etc/ocs/ocs-live.conf ] && . /etc/ocs/ocs-live.conf
 
+# Functions
+USAGE() {
+    echo "$ocs - Program to start saving or restoring image in Clonezilla live"
+    echo "Usage:"
+    echo "To run $ocs:"
+    echo "$ocs"
+    echo "Ex:"
+    echo "To start saving or restoring image in Clonezilla live, run"
+    echo "   $ocs"
+    echo "If what you want is just saving, use \"ocs-live-save\" instead of this program."
+    echo "If what you want is just restoring, use \"ocs-live-restore\" instead of this program."
+} # end of USAGE
+
+####################
+### Main program ###
+####################
+
+ocs=`basename $0`
+#
+check_if_root
+#
+while [ $# -gt 0 ]; do
+ case "$1" in
+   -*)     echo "${0}: ${1}: invalid option" >&2
+           USAGE >& 2
+           exit 2 ;;
+   *)      break ;;
+ esac
+done
+
 # Get the live media mount point.
 get_live_media_mnt_point
 
