ocs_live_u-bootable_rawdisk: enhance script
 - Add -o | --output option to specify the output filename
 - Adapt to OCS "toram" mode: modify the workflow and the path of
   repack-raw_info.txt

diff --git a/sbin/ocs-live-u-bootable-rawdisk b/sbin/ocs-live-u-bootable-rawdisk
--- a/sbin/ocs-live-u-bootable-rawdisk
+++ b/sbin/ocs-live-u-bootable-rawdisk
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #=====================================================================
-#  File:   ocs-live-u-bootable-rawdisk
+#  File:   ocs-live-gen-ubrd (say: ocs-live generate u-bootable raw disk)
 #  Author: Ceasar Sun
 #  Co-Translator: Jouni Järvinen (@rautamiekka)
 #  Desc:   Merge OCS zip and U-boot enabled bootable raw image as a new U-boot enabled OCS live raw disk.
@@ -34,10 +34,12 @@ OCS_ZIP=""
 LOOP_DEVICE=""
 KPARTX_MAP=""
 DOWNLOADED_TEMPLATE=""
+OUTPUT_RAWDISK=""
 FULL_SELF_CLI="$BASH_SOURCE$(printf " %q" "$@")"
 
 DEBUG_MODE=false
 VERBOSE_MODE=
+THIS_VERSION="1.0.0-14"
 
 #---------------------------#
 #  Functions                #
@@ -68,6 +70,7 @@ Mandatory arguments to long options are mandatory for short options too.
    OCS_ZIP_FILE                     Required, OCS zip file
    -bt|--bootable_template=FILE     OCS bootable template raw image。
                                     Script will use '${DEFAULT_BOOTABLE_RAW_TEMPLATE}' as default template if none is assigned. 
+   -o|--output=FILE                 File name of output。
    -d|--debug                       Debug mode : to keep TMPDIR_ROOT
    -v|--verbose                     Verbose mode
    -h|--help                        Show help
@@ -75,7 +78,7 @@ Mandatory arguments to long options are mandatory for short options too.
 Example:
  ~$ sudo $(basename $0) clonezilla-live-3.2.2-5-riscv64.zip	
  ~$ sudo $(basename $0) my_repack_ocs.zip --bootable_template /path/to/boot.raw --debug
- ~$ sudo $(basename $0) my_repack_ocs.zip -d -v -bt /path/to/boot.raw 
+ ~$ sudo $(basename $0) my_repack_ocs.zip -d -v -bt /path/to/boot.raw -o /path/to/my-output.img
 EOF
 }
 
@@ -145,6 +148,11 @@ while [[ $# -gt 0 ]]; do
             BOOTABLE_TEMPLATE_RAWDISK="${2:-}"
             [[ -z "${BOOTABLE_TEMPLATE_RAWDISK}" ]] && die "Missing argument for --bootable_template"
             [[ ! -e "${BOOTABLE_TEMPLATE_RAWDISK}" ]] && die "Template file : '${BOOTABLE_TEMPLATE_RAWDISK}' doesn't existed !"
+            shift 2
+            ;;
+        -o|--output)
+            OUTPUT_RAWDISK="${2:-}"
+            [[ -z "${OUTPUT_RAWDISK}" ]] && die "Missing argument for --output"
             shift 2
             ;;
         -d|--debug)
@@ -240,13 +248,42 @@ done
 mkdir ${VERBOSE_MODE} -p "${MOUNT_POINT}"
 echo "Create Temp directory : ${MOUNT_POINT}"
 
+#---------------------------#
+#  1.1 Unzip OCS zip then rsync contents   #
+#---------------------------#
+echo "Extracting OCS zip ..."
+TMP_UNZIP="${TMPDIR_ROOT}/unzipped"
+mkdir ${VERBOSE_MODE} -p "${TMP_UNZIP}"
+unzip $( [[ $VERBOSE_MODE ]] || echo "-q" ) "${OCS_ZIP}" -d "${TMP_UNZIP}" || die "unzip failed"
+
+#--------------------------------#
+#  1.2 Write repack info to file  #
+#--------------------------------#
+INFO_FILE="${TMP_UNZIP}/live/repack-raw_info.txt"
+{
+    echo "=== Repack Info  ==="
+    echo "Date                  : $(date '+%Y-%m-%d %H:%M:%S')"
+    echo "Version               : ${THIS_VERSION}"
+    echo "Original OCS Zip      : $(md5sum ${OCS_ZIP})"
+    echo "Template RAM MD5SUM   : $(md5sum ${BOOTABLE_TEMPLATE_RAWDISK})"
+    echo "Loop Device           : ${LOOP_DEVICE}"
+    echo "Bootfs Mapper         : ${KPARTX_MAP}"
+    echo "Full Self Command     : ${FULL_SELF_CLI}"
+    echo "=== End of info ==="
+} > "${INFO_FILE}"
+
+echo "Write Repack Info into: ${INFO_FILE}"
+
 #---------------------------------------#
-#  2. Deat with "bootfs" in raw device  #
+#  2. Deal with U-bootable raw device   #
 #---------------------------------------#
 TMP_RAW="${TMPDIR_ROOT}/raw_image.img"
 echo "Copying bootable raw image to temporary file ..."
 cp -a ${VERBOSE_MODE} "${BOOTABLE_TEMPLATE_RAWDISK}" "${TMP_RAW}"
 
+#---------------------------------------#
+#  2.1 Create loop and mapper device    #
+#---------------------------------------#
 echo "Setting up loop device ..."
 LOOP_DEVICE=$(losetup ${VERBOSE_MODE} -f --show "${TMP_RAW}")
 [[ -z "${LOOP_DEVICE}" ]] && die "Create loop device failed ..."
@@ -255,6 +292,9 @@ echo "Creating partition mappings with kpartx ..."
 kpartx ${VERBOSE_MODE} -a -s "${LOOP_DEVICE}"
 sleep 1   # wait for device mapper
 
+#----------------------------------------------#
+#  2.2 Find "bootfs" then mount ,sync from ZIP  #
+#----------------------------------------------#
 # Search device mapper id which the partition "name" = "bootfs"
 KPARTX_MAP="/dev/mapper/$(lsblk -ln -o NAME,LABEL ${LOOP_DEVICE}  \
     | awk -v bootfs_part_name="$BOOTFS_PART_NAME" '$2 == bootfs_part_name {print $1}' \
@@ -265,37 +305,12 @@ KPARTX_MAP="/dev/mapper/$(lsblk -ln -o NAME,LABEL ${LOOP_DEVICE}  \
 echo "Mounting partition ${KPARTX_MAP} to ${MOUNT_POINT} ..."
 mount ${VERBOSE_MODE} "${KPARTX_MAP}" "${MOUNT_POINT}"
 
-#---------------------------#
-#  3. Unzip OCS zip then rsync contents   #
-#---------------------------#
-echo "Extracting OCS zip ..."
-TMP_UNZIP="${TMPDIR_ROOT}/unzipped"
-mkdir ${VERBOSE_MODE} -p "${TMP_UNZIP}"
-unzip $( [[ $VERBOSE_MODE ]] || echo "-q" ) "${OCS_ZIP}" -d "${TMP_UNZIP}" || die "unzip failed"
-
 echo "Rsyncing extracted files to mounted partition ..."
 rsync -a ${VERBOSE_MODE} "${TMP_UNZIP}/." "${MOUNT_POINT}/" || die "rsync failed"
 #cp ${VERBOSE_MODE} -a "${TMP_UNZIP}/." "${MOUNT_POINT}/" || die "copy failed"
 
-#--------------------------------#
-#  4. Write repack info to file  #
-#--------------------------------#
-INFO_FILE="${MOUNT_POINT}/repack-raw_info.txt"
-{
-    echo "=== Repack Info  ==="
-    echo "Date                  : $(date '+%Y-%m-%d %H:%M:%S')"
-    echo "Original OCS Zip      : ${OCS_ZIP}"
-    echo "Bootable Raw Template : ${BOOTABLE_TEMPLATE_RAWDISK}"
-    echo "Loop Device           : ${LOOP_DEVICE}"
-    echo "Bootfs Mapper         : ${KPARTX_MAP}"
-    echo "Full Self Command     : ${FULL_SELF_CLI}"
-    echo "=== End of info ==="
-} > "${INFO_FILE}"
-
-echo "Write Repack Info into: ${INFO_FILE}"
-
 #---------------------------------------#
-#  5. Umount then rename raw device     #
+#  3. Umount , remove loop device       #
 #---------------------------------------#
 echo "Syncing filesystem ..."
 sync
@@ -311,7 +326,7 @@ losetup ${VERBOSE_MODE} -d "${LOOP_DEVICE}" || echo "Warning: losetup -d failed"
 
 # Generate its output name
 OCS_BASENAME="$(basename "${OCS_ZIP}" .zip)"   # Remove suffix '.zip'
-FINAL_IMG="${OCS_BASENAME}_u-bootable.img"
+[[ -z "${OUTPUT_RAWDISK}" ]] && FINAL_IMG="${OCS_BASENAME}_u-bootable.img" || FINAL_IMG="${OUTPUT_RAWDISK}"
 
 # If target exists, ask before overwrite
 if [[ -e "${FINAL_IMG}" ]]; then
@@ -319,6 +334,9 @@ if [[ -e "${FINAL_IMG}" ]]; then
     [[ "${ans}" =~ ^[Yy]$ ]] || mv ${VERBOSE_MODE} "${FINAL_IMG}" "${FINAL_IMG}_$$"
 fi
 
+#---------------------------------------#
+#  4. Rename output ,show dd command    #
+#---------------------------------------#
 echo "Renaming temporary raw image to ${FINAL_IMG} ..."
 mv ${VERBOSE_MODE} "${TMP_RAW}" "${FINAL_IMG}"
 
