Add option "-c" in ocs-live-preload.

diff --git a/sbin/ocs-live-preload b/sbin/ocs-live-preload
--- a/sbin/ocs-live-preload
+++ b/sbin/ocs-live-preload
@@ -325,6 +325,28 @@ convert_dos_format_script_from_cp_rv_list() {
 #################
 ##### MAIN ######
 #################
+
+ocs_file="$0"
+ocs=`basename $ocs_file`
+#
+while [ $# -gt 0 ]; do
+ case "$1" in
+   -c|--cmdline-file)
+      shift
+      if [ -z "$(echo $1 |grep ^-.)" ]; then
+        # skip the -xx option, in case 
+        cmdl_file="$1"
+        shift
+      fi
+      [ -z "$cmdl_file" ] && echo "-c is used, but no cmdl_file assigned." && exit 1
+      ;;
+   -*)     echo "${0}: ${1}: invalid option" >&2
+           USAGE >& 2
+           exit 2 ;;
+   *)      break ;;
+ esac
+done
+
 check_if_root
 ask_and_load_lang_set
 
