Fixing some typos

diff --git a/sbin/ocs-install-grub b/sbin/ocs-install-grub
--- a/sbin/ocs-install-grub
+++ b/sbin/ocs-install-grub
@@ -32,7 +32,7 @@ USAGE() {
     echo
     echo "OPTION:"
     echo "-g, --grub-version VER  Assign the grub version as VER (1 or 2)"
-    echo "-s, --selected-hd  DISk Assign the disk to search for _only_, i.e. not to search those not in the lists. This is used for not to touch those disk which are not restored. It can be with or without /dev/, e.g, /dev/sda or sda." 
+    echo "-s, --selected-hd  DISK Assign the disk to search for _only_, i.e. not to search those not in the lists. This is used for not to touch those disk which are not restored. It can be with or without /dev/, e.g, /dev/sda or sda."
     echo "-p, --selected-parts PARTITION  Assign the partitions to search for _only_, i.e. not to search those not in the lists. This is used for not to touch those partitions which are not restored. It can be with or without /dev/, e.g., /dev/sda1 or sda For multiple partitions, use something like \"sda1 sda2\""
     echo "-n, --no-check-before-install   By default we check if grub is already in the boot loader. If so, we continue to run grub-install. This option will go without checking."
     echo "Ex:"
@@ -124,7 +124,7 @@ do_run_grub1_from_running_os() {
       echo "Running: $grub_install_exec $grub_no_floopy_opt --root-directory=$hd_img /dev/$boot_loader_pos"
       $grub_install_exec $grub_no_floopy_opt --root-directory=$hd_img /dev/$boot_loader_pos
       rc="$?"
-      # Remove the device.map in case it provents the restored OS fails to run update-grub due to different boot device name (e.g. sda <-> hda issue)
+      # Remove the device.map in case it prevents the restored OS fails to run update-grub due to different boot device name (e.g. sda <-> hda issue)
       [ -f "$hd_img/boot/grub/device.map" ] && rm -f $hd_img/boot/grub/device.map
       
       check_grub1_config_file $hd_img
@@ -236,7 +236,7 @@ show_grub1_ext4_warning () {
         [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
         return 3
       else
-        # Otherwise distributios...
+        # Otherwise distributions...
         [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
         echo "Warning! Found grub partition ($grub_pt_) file system is ext4! Not all versions of grub 1 supports file system ext4!"
         [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
@@ -402,7 +402,7 @@ fdisk -l /dev/$grub_hd &>/dev/null
 # This ocs-install-grub program is only for BIOS/MBR boot loader,
 # not for EFI unless it's a GPT disk with a special "bios_boot" partition
 # exists in the machine using legacy BIOS.
-if ! `is_mbr_partitition_table_disk /dev/$grub_hd`; then
+if ! `is_mbr_partition_table_disk /dev/$grub_hd`; then
   # In this case, it might be GPT or some other non MBR (msdos) case.
   if `is_gpt_disk_with_bios_boot_part_in_legacy_bios /dev/$grub_hd`; then
     # This is the case for a GPT disk with a special "bios_boot" partition
@@ -445,7 +445,7 @@ if [ "$check_before_install" = "yes" ]; then
     # fSfSfUfh
     # Invalid partition table
     # Error loading operating system
-    # Missing operating system <----- commone one
+    # Missing operating system <----- common one
     # ======================
     # (2) Instead, the grub boot loader is on root partition (/dev/sda2) for OpenSuSE 13.2 default installation
     # root@debian:/tmp# dd if=/dev/sda2 bs=512 count=1 2>/dev/null |strings
@@ -513,7 +513,7 @@ if [ -n "$($grub_install_exec --help | grep "\--no-floppy")" ]; then
   grub_no_floopy_opt="--no-floppy"
 fi
 # Check if /boot is in its own partition, if so, different mount point.
-# grub root-directory must have "/boot/". If no "/boot/", it must be the grub partition itself (i.e. a separate partition will be mounted as /boot, and it conains /grub/ in the partition.)
+# grub root-directory must have "/boot/". If no "/boot/", it must be the grub partition itself (i.e. a separate partition will be mounted as /boot, and it contains /grub/ in the partition.)
 if [ ! -d "$hd_img/boot/" ]; then
    # In this case, /boot must exist in its own partition, 
    # not same partition with / (root partition).
@@ -524,7 +524,7 @@ if [ ! -d "$hd_img/boot/" ]; then
    echo "There is a separate boot partition in target device. Trying to mount root partition for $grub_install_exec to work with that..."
    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
    # Important! We have to mount the root dir first. Otherwise in FC6, CentOS 5 or later, grub-install will refuse to do that without root device. It will show the error message like: "Could not find device for /mnt"... For Debian or Ubuntu, no such problem. 
-   # Actually we can modify /sbin/grub-install (grub-0.97-13) in FC6 or Centos5:
+   # Actually we can modify /sbin/grub-install (grub-0.97-13) in FC6 or CentOS 5:
    # -----------
    # ...
    # # Get the root drive.
