Put efiboot.img in /boot/grub/ inside zip file.

diff --git a/sbin/ocs-live-dev b/sbin/ocs-live-dev
--- a/sbin/ocs-live-dev
+++ b/sbin/ocs-live-dev
@@ -28,8 +28,6 @@ clonezilla_iso_branch="alternative"
 clonezilla_iso_arch_tag="-i386"
 # Where the MD5SUM could be found for the above iso file. This has to match $clonezilla_iso_branch and $clonezilla_iso_arch_tag
 DEBIAN_ISO_ETC_PATH="http://free.nchc.org.tw/clonezilla-live/alternative/stable/"
-# Flag to put EFI booting image
-enabled_EFI="true"
 #
 live_boot_menu_opt_raw=""
 # To use image exists when creating recovery device (e.g. /dev/sdg1). the image might already exist (copied or created on the device before). For other mode, image is copied or linked in this program.
@@ -525,13 +523,11 @@ fi
 
 # Check if EFI boot could be supported.
 if [ ! -e "$DEBIAN_ISO_TMP/EFI/boot/bootx64.efi" ]; then
-  # We only check bootx64.efi since bootx86.efi is optional.
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-  echo "Warning! /EFI/boot/bootx64.efi was not found in template Clonezilla live!"
-  echo "The generated $target_iso will not support EFI boot!"
+  [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+  echo "/EFI/boot/bootx64.efi was not found in template Clonezilla live!"
   [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-  sleep 5
-  enabled_EFI="false"
+  echo "$msg_program_stop"
+  exit 1
 fi
 
 if [ "$target_mode" = "release_file" ]; then
@@ -919,53 +915,49 @@ else
   quiet_switch=""
 fi
 
-if [ "$enabled_EFI" = "true" ]; then
-  # Build the EFI boot image. This is especially for iso file. Not for USB stick. However, here we still prepare the file so that later it's easier to use genisoimage to create the EFI-enabled iso.
-  # The following codes are referred from Fedora anaconda's mk-images.efi
-  # http://fedorapeople.org/cgit/karsten/public_git/anaconda.git/plain/scripts/mk-images.efi
-  # Ref: https://fedoraproject.org/wiki/User:Pjones/BootableCDsForBIOSAndUEFI#New_UEFI.2FBIOS_hybrid_method
-  EFI_BOOTIMG_TMP="$(mktemp -d /tmp/efi-boot.XXXXXX)"
-  EFI_BOOTTREE="$DEBIAN_ISO_TMP/EFI"
-  EFI_IMGTREE="$USB_TMP/EFI/images"
-  EFI_IMG="$EFI_IMGTREE/efiboot.img"
-  mkdir -p $EFI_IMGTREE
-  rm -rf $USB_TMP/.disk
-  rm -f $EFI_IMG
-  
-  BOOTDISKSIZE="$(LC_ALL=C du -kcs $EFI_BOOTTREE | tail -n1 | awk '{print $1}')"
-  BOOTDISKSIZE="$(LC_ALL=C echo "scale=0; $BOOTDISKSIZE * 1.03 / 1" | bc -l)"
-  echo "The size of the $EFI_IMG is $BOOTDISKSIZE"
-  mkdosfs -n OCS-EFI -C $EFI_IMG $BOOTDISKSIZE >/dev/null
-  mount -o loop,shortname=winnt,umask=0077 -t vfat $EFI_IMG $EFI_BOOTIMG_TMP
-  mkdir -p $EFI_BOOTIMG_TMP/EFI/
-  if [ "$live_efi_boot_loader" = "grub" ]; then
-    # In this case, bootx64.efi is in $EFI_BOOTTREE/, but we should exclude the existing $EFI_BOOTTREE/images/efiboot.img
-    # However, when mkdosfs we do not exclude $EFI_BOOTTREE/images/efiboot.img, so the size might be counted. It's better to put efiboot.img not in /EFI/ in the future.
-    rsync -a --exclude images/ $EFI_BOOTTREE/* $EFI_BOOTIMG_TMP/EFI/
-  elif [ "$live_efi_boot_loader" = "syslinux" ]; then
-    # In this case, bootx64.efi is copied in $USB_TMP/EFI/, we should do something similar with ocs-gen-grub2-efi-bldr
-    rsync -a --exclude images/ $USB_TMP/EFI/* $EFI_BOOTIMG_TMP/EFI/
-    # TODO similar to ocs-gen-grub2-efi-bldr, create a syslinux.cfg to include /syslinux/syslinux.cfg.
-  fi
-  umount $EFI_BOOTIMG_TMP
-  if [ -d "$EFI_BOOTIMG_TMP" -a -n \
-  	"$(echo $EFI_BOOTIMG_TMP | grep -e "efi-boot")" ]; then
-    rm -rf $EFI_BOOTIMG_TMP
-  fi
-  
-  # Create an info file for grub2 to autodetect the cd root
-  # Ref: http://www.sysresccd.org/forums/viewtopic.php?f=5&t=4410
-  mkdir $USB_TMP/.disk
-  echo -n "[Clonezilla]" > $USB_TMP/.disk/info
-  
-  # For Ubuntu uEFI secure boot signed grubx64.efi, it will search /boot/grub/grub.cfg instead of what we have (/EFI/boot/grub.cfg). Although we do not use Ubuntu as the underlaying OS, we still keep this for the future just in case.
-  mkdir -p $USB_TMP/boot/grub/
-  cat <<-EFI_END > $USB_TMP/boot/grub/grub.cfg
+# //NOTE//
+# Build the EFI boot image. This is especially for iso file. Not for USB stick. However, here we still prepare the file so that later it's easier to use genisoimage to create the EFI-enabled iso.
+# The following codes are referred from Fedora anaconda's mk-images.efi
+# http://fedorapeople.org/cgit/karsten/public_git/anaconda.git/plain/scripts/mk-images.efi
+# Ref: https://fedoraproject.org/wiki/User:Pjones/BootableCDsForBIOSAndUEFI#New_UEFI.2FBIOS_hybrid_method
+EFI_BOOTIMG_TMP="$(mktemp -d /tmp/efi-boot.XXXXXX)"
+EFI_BOOTTREE="$DEBIAN_ISO_TMP/EFI"
+EFI_IMG="$USB_TMP/boot/grub/efiboot.img"
+rm -rf $USB_TMP/.disk
+rm -f $EFI_IMG
+
+BOOTDISKSIZE="$(LC_ALL=C du -kcs $EFI_BOOTTREE/boot/boot*.efi | tail -n1 | awk '{print $1}')"
+BOOTDISKSIZE="$(LC_ALL=C echo "scale=0; $BOOTDISKSIZE * 1.02 / 1" | bc -l)"
+echo "The size of the $EFI_IMG is $BOOTDISKSIZE"
+mkdosfs -n OCS-EFI -C $EFI_IMG $BOOTDISKSIZE >/dev/null
+mount -o loop,shortname=winnt,umask=0077 -t vfat $EFI_IMG $EFI_BOOTIMG_TMP
+mkdir -p $EFI_BOOTIMG_TMP/EFI/boot/
+if [ "$live_efi_boot_loader" = "grub" ]; then
+  # In this case, bootx64.efi is in $EFI_BOOTTREE/
+  rsync -a $EFI_BOOTTREE/boot/boot*.efi $EFI_BOOTIMG_TMP/EFI/boot/
+elif [ "$live_efi_boot_loader" = "syslinux" ]; then
+  # In this case, bootx64.efi is copied in $USB_TMP/EFI/, we should do something similar with ocs-gen-grub2-efi-bldr
+  rsync $USB_TMP/boot/boot*.efi $EFI_BOOTIMG_TMP/EFI/boot/
+  # TODO similar to ocs-gen-grub2-efi-bldr, create a syslinux.cfg to include /syslinux/syslinux.cfg.
+fi
+umount $EFI_BOOTIMG_TMP
+if [ -d "$EFI_BOOTIMG_TMP" -a -n \
+	"$(echo $EFI_BOOTIMG_TMP | grep -e "efi-boot")" ]; then
+  rm -rf $EFI_BOOTIMG_TMP
+fi
+
+# Create an info file for grub2 to autodetect the cd root
+# Ref: http://www.sysresccd.org/forums/viewtopic.php?f=5&t=4410
+mkdir $USB_TMP/.disk
+echo -n "[Clonezilla]" > $USB_TMP/.disk/info
+
+# For Ubuntu uEFI secure boot signed grubx64.efi, it will search /boot/grub/grub.cfg instead of what we have (/EFI/boot/grub.cfg). Although we do not use Ubuntu as the underlaying OS, we still keep this for the future just in case.
+mkdir -p $USB_TMP/boot/grub/
+cat <<-EFI_END > $USB_TMP/boot/grub/grub.cfg
 # This file is for compatibility to Ubuntu Linux's uEFI secure boot. 
 # The real config file for grub is /EFI/boot/grub.cfg.
 configfile /EFI/boot/grub.cfg
 EFI_END
-fi
 
 # Prepare the sort file for genisoimage. Although we do not use genisoimage here, however, we'd like the file created by ocs-live-dev is the same with that of ocs-iso. So it's easier to convert zip file to iso file.
 # Therefore we still put the file iso_sort.txt here.
