Support bitlocker device as image repository.
Support mounting bitlocker device as image repository.
Thanks to fiddyschmitt for requesting this.
Ref: https://github.com/stevenshiau/clonezilla/issues/58

diff --git a/sbin/prep-ocsroot b/sbin/prep-ocsroot
--- a/sbin/prep-ocsroot
+++ b/sbin/prep-ocsroot
@@ -129,6 +129,44 @@ do_mount_local_dev() {
              esac
            fi
 	   ;;
+     bitlocker|BitLocker) 
+	   # $pre_bitlocker_path is from drbl-ocs.conf.
+	   mkdir -p $pre_bitlocker_path
+           ask_="true"
+           while [ "$ask_" = "true" ]; do
+             [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+             echo "Mounting BitLocker partition by:"
+	     cmd="dislocker /dev/$target_part -u -- $pre_bitlocker_path"
+             [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+	     echo "Running: $cmd"
+	     eval $cmd
+             rc=$?
+	     if [ "$rc" -eq 0 ]; then
+	       cmd="mount -o loop $pre_bitlocker_path/dislocker-file $ocsroot"
+	       echo "Running: $cmd"
+	       eval $cmd
+               rc=$?
+	     fi
+             if [ "$rc" -ne 0 ]; then
+               echo $msg_delimiter_star_line
+               [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+               echo "$msg_unable_to_mnt_ocsroot. $msg_do_u_want_to_do_it_again"
+               [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+               echo -n "[Y/n] "
+               read run_again_ans
+               case "$run_again_ans" in
+                 n|N|[nN][oO]) ask_="false" ;;
+                            *) ask_="true" 
+			       umount $ocsroot 2>/dev/null
+			       umount /dev/$target_part
+			       ;;
+               esac
+             else
+               ask_="false"
+             fi
+           done
+           [ "$chk_ocsroot_mountpont" = "yes" ] && check_if_ocsroot_a_mountpoint
+	   ;;
      hfsplus) 
            [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
            echo "$msg_warning_mount_hfsplus_writable"
diff --git a/scripts/sbin/ocs-functions b/scripts/sbin/ocs-functions
--- a/scripts/sbin/ocs-functions
+++ b/scripts/sbin/ocs-functions
@@ -3989,6 +3989,8 @@ task_postprocessing() {
       ;;
   esac
 
+  unmount_dislocker_mount_point_if_necessary
+
   #
   echo "Now syncing - flush filesystem buffers..." | tee --append ${OCS_LOGFILE}
   sync;sync;sync | tee --append ${OCS_LOGFILE}
@@ -15235,3 +15237,34 @@ clean_raid_metadata_in_disk() {
     [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
   fi
 } # end of clean_raid_metadata_in_disk
+#
+unmount_dislocker_mount_point_if_necessary(){
+  # Function to unmount dislocker (bitlocker) device
+  local im dir_2_umount cmd_ rc
+  # root@debian:~# mount |grep -Ew /home/partimag
+  # /tmp/ocsroot_bitlocker_root/dislocker-file on /home/partimag type fuseblk (rw,noatime,user_id=0,group_id=0,allow_other,blksize=4096)
+  if [ -z "$(LC_ALL=C mount | grep -Ew "${ocsroot}/*" |\
+	  grep -Ewo "dislocker-file")" ]; then
+    # Not a dislocker device for ocsroot.
+    echo "The mounted bitlocker device was not found. Skip unmounting it."
+    return 3
+  fi
+  dir_2_umount=" $ocsroot $pre_ocsroot_path $pre_bitlocker_path"
+  for im in $dir_2_umount; do
+    if mountpoint $im &>/dev/null; then
+      cmd_="umount $im"
+      echo "Running: $cmd_"
+      eval $cmd_
+      rc=$?
+      if [ "$rc" -ne 0 ]; then
+        # Try to use umount -l to unmount it
+	# pkill -9 mount.ntfs
+	# pkill -9 ntfs-3g
+	# sleep 1
+        cmd_="umount -l $im"
+        echo "Running: $cmd_"
+        eval $cmd_
+      fi
+    fi
+  done
+} # end of unmount_dislocker_mount_point_if_necessary
