mdisks-checksum: add a mode "check-then-label"
Add a mode "check-then-label" or "ctl".

diff --git a/samples/mdisks-checksum b/samples/mdisks-checksum
--- a/samples/mdisks-checksum
+++ b/samples/mdisks-checksum
@@ -40,7 +40,7 @@ USAGE() {
   echo "-n, --no-resize    Do not resize in the destination disk. Keep the size as that from source image. This implies the options '-k1 -r -icds' will not be used for clonezilla's program ocs-sr."
   echo "-r, --parallel  Run the checksum inspection in parallel. The inspection for all partitions in a disk will be run in parallel. Maybe it's not a good idea if too many partitions and it might casue too many I/Os then less effiency."
   echo "-p, --label-prefix PREFIX  Set the label prefix for the destination partitions when restoring. This is only for mode 'restore', and it will be used to create a sequential label names for all the partitions on destination disks, like my-image_01p1, my-image_01p2 for disk /dev/sda1, and /dev/sda2, respectively."
-  echo "MODE is for saving, restoring or checking. Available: save, restore, check."
+  echo "MODE is for saving, restoring, checking, labeling. Available: save, restore, check, check-then-label (or ctl)."
   echo "IMAGE_NAME is the image dir name, not absolute path"
   echo "DEVICE is the device name, e.g. sda, sda... When MODE is 'save', only one disk is allowed. While when MODE is 'restore', more than one disks are accetable."
   echo "If IMAGE_NAME and DEVICE are not assigned. An dialog menu will be shown to allow inputing or choosing."
@@ -168,15 +168,15 @@ do_restore_or_check_mode_check() {
 } # end of do_restore_or_check_mode_check
 #
 do_mdisk_restore_task() {
+  # (1) Deploy the image to multiple destination disks
+  # (2) Label the destination partitions
+  # (3) Put checksum results in image repository and destination disk.
+  #     Format: ${image}_${part_label}_md5_results.txt (e.g. Speed_LA01p1_md5_results.txt
   local img="$1"
   local dest_dsk="$2"
   local tmpd_dest
   rm -f /var/log/*sum-results.log
   ocs-restore-mdisks $batch_opt -p "-g auto $resize_opt -e1 auto -e2 -nogui -j2 -cmf -scr -p true" $img $dest_dsk | tee -a /var/log/${ocs}.log
-  # (1) Put checksum file. Format: $image_name-$time (e.g. HOWL_09Oct15-171023.md5)
-  # In image dir, it's like: sda1.files-md5sum.info.gz
-  
-  # (2) Label the partition, and put the inspection results of checksum to $ocsroot and / in every restored disk.
   for idsk in $dest_dsk; do 
     echo "Searching for data partition(s)..." | tee -a /var/log/${ocs}-${idsk}.log
     BACKUP_DEVS=""
@@ -225,15 +225,14 @@ do_mdisk_restore_task() {
 } # end of do_mdisk_restore_task
 #
 do_mdisk_checksum_match_task() {
+  # (1) Inspect the checksum for destination disks.
+  # (2) Put checksum results in image repository and destination disk.
+  #     Format: ${image}_${part_label}_md5_results.txt (e.g. Speed_LA01p1_md5_results.txt
   local img="$1"
   local dest_dsk="$2"
   local tmpd_dest LABEL
   rm -f /var/log/*sum-results.log
   ocs-match-checksum $parallel_opt $img $dest_dsk | tee -a /var/log/${ocs}.log
-  # (1) Put checksum file. Format: $image_name-$time (e.g. HOWL_09Oct15-171023.md5)
-  # In image dir, it's like: sda1.files-md5sum.info.gz
-  
-  # (2) Label the partition, and put the inspection results of checksum to $ocsroot and / in every restored disk.
   for idsk in $dest_dsk; do 
     echo "Searching for data partition(s)..." | tee -a /var/log/${ocs}-${idsk}.log
     BACKUP_DEVS=""
@@ -278,14 +277,72 @@ do_mdisk_checksum_match_task() {
   done
 } # end of do_mdisk_checksum_match_task
 #
+do_mdisk_checksum_match_and_label_task() {
+  # (1) Inspect the checksum for destination disks.
+  # (2) Label the destination partitions
+  # (3) Put checksum result in image repository and destination disk.
+  #     Format: ${image}_${part_label}_md5_results.txt (e.g. Speed_LA01p1_md5_results.txt
+  local img="$1"
+  local dest_dsk="$2"
+  local tmpd_dest LABEL
+  rm -f /var/log/*sum-results.log
+  ocs-match-checksum $parallel_opt $img $dest_dsk | tee -a /var/log/${ocs}.log
+  for idsk in $dest_dsk; do 
+    echo "Searching for data partition(s)..." | tee -a /var/log/${ocs}-${idsk}.log
+    BACKUP_DEVS=""
+    get_known_partition_proc_format $idsk data
+    target_parts="$BACKUP_DEVS"
+    # Strip the single white space which should be nothing. Thanks to Borksoft.
+    target_parts="$(echo $target_parts | sed -e "s/^  *$//")"
+    tmpd_dest="$(mktemp -d /tmp/tmpd_dest.XXXXXX)"
+    trap "[ -d "$tmpd_dest" ] && umount $tmpd_dest &>/dev/null" HUP INT QUIT TERM EXIT
+    for iprt in $target_parts; do
+      pt="$(get_part_number "$iprt")"
+      initial_no="$(LC_ALL=C printf "%.2u" $initial_no)"  # e.g. 2 -> 02
+      part_label=${part_label_prefix}${initial_no}p${pt}
+      echo "Labeling /dev/${idsk}${pt} as $part_label" | tee -a /var/log/${ocs}-${idsk}.log
+      ocs-label-dev /dev/${idsk}${pt} $part_label | tee -a /var/log/${ocs}-${idsk}.log
+  
+      # Find the checksum
+      # Output for get_chksum_info_from_img: chksum_cmd, chksum_file
+      get_chksum_info_from_img "$ocsroot/$img" "*" 
+      if [ -z "$chksum_cmd" ]; then
+        [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+        echo "No any checksum file for files in /dev/$iprt was found in image dir $ocsroot/$img." | tee --append ${OCS_LOGFILE}
+        echo "No way to copy checksum to $ocsroot and /dev/$iprt." | tee --append ${OCS_LOGFILE}
+        [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+        continue
+      fi
+      if [ -e "/var/log/${iprt}-${chksum_cmd}-results.log" ]; then
+        cp /var/log/${iprt}-${chksum_cmd}-results.log $ocsroot/${img}_${part_label}_md5_results.txt 2>&1 | tee -a /var/log/${ocs}-${idsk}.log
+        mount /dev/$iprt $tmpd_dest | tee -a /var/log/${ocs}-${idsk}.log
+        cp /var/log/${iprt}-${chksum_cmd}-results.log $tmpd_dest/${img}_${part_label}_md5_results.txt 2>&1 | tee -a /var/log/${ocs}-${idsk}.log
+        umount /dev/$iprt | tee -a /var/log/${ocs}-${idsk}.log
+      else
+        fs="$(LC_ALL=C ocs-get-part-info /dev/${iprt} fs)"
+        [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+        echo "File /var/log/${iprt}-${chksum_cmd}-results.log not found." | tee -a /var/log/${ocs}-${idsk}.log
+        [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+	echo "Maybe the file system \"$fs\" in /dev/${iprt} is not supported by Linux kernel? Or there are no any regular files in /dev/${iprt}?" | tee -a /var/log/${ocs}-${idsk}.log
+      fi
+      initial_no="$(echo "scale=0; $initial_no + 1" | bc)"
+    done
+    if [ -d "$tmpd_dest" -a "$(echo "$tmpd_dest" | grep -E /tmp/tmpd_dest\.)" ]; then
+      rm -rf $tmpd_dest
+    fi
+  done
+} # end of do_mdisk_checksum_match_and_label_task
+#
 do_mdisk_save_task() {
+  # (1) Save the image from source device
+  # (2) Put checksum file in image repository.
+  #     File name format: $image_name-$time (e.g. HOWL_09Oct15-171023.md5)
+  #     Merge them to one file if more than one checksum files exist.
   local img="$1"
   local src_dsk="$2"
   # (1) Save the disk as image
   ocs-sr -q2 $batch_opt $nogui_opt -j2 -gmf -z1p -i 4096 -p true savedisk $img $src_dsk
-  # Put checksum file. Format: $image_name-$time (e.g. HOWL_09Oct15-171023.md5)
-  # In image dir, it's like: sda1.files-md5sum.info.gz
-  # Merge them to one file if more than one checksum files exist.
+  #
   time_now="$(LC_ALL=C date +%d%b%y-%H%M%S)"
   rm -f $ocsroot/${img}-${time_now}.md5
   echo "Preparing checksum file $ocsroot/${img}_${time_now}.md5... "
@@ -393,7 +450,7 @@ if [ -z "$task_mode" ]; then
 else
   # Check the input
   case "$task_mode" in
-    "save"|"restore"|"check") true;;
+    "save"|"restore"|"check"|"ctl"|"check-then-label") true;;
     *)  show_unknown_mode_then_exit;;
   esac
 fi
@@ -407,6 +464,8 @@ case "$task_mode" in
   save)    do_save_mode_ask_image_dev_if_required;;
   restore) do_restore_or_check_mode_ask_image_dev_if_required;;
   check)   do_restore_or_check_mode_ask_image_dev_if_required;;
+  ctl|check-then-label)   
+	   do_restore_or_check_mode_ask_image_dev_if_required;;
 esac
 
 # check if the device exists
@@ -426,6 +485,10 @@ case "$task_mode" in
 	   ;;
   check)   do_restore_or_check_mode_check
            do_mdisk_checksum_match_task "$img_name" "$disk"
+	   ;;
+  ctl|check-then-label)   
+	   do_restore_or_check_mode_check
+           do_mdisk_checksum_match_and_label_task "$img_name" "$disk"
 	   ;;
   *)       show_unknown_mode_then_exit
 	   ;;
