Set CPUs offline/online jobs in background

diff --git a/setup/files/ocs/live-hook/udev/cpu_offline b/setup/files/ocs/live-hook/udev/cpu_offline
--- a/setup/files/ocs/live-hook/udev/cpu_offline
+++ b/setup/files/ocs/live-hook/udev/cpu_offline
@@ -9,7 +9,7 @@ echo "Disabling SMP-like behavior before udev is started..."
 for cpu in `ls -dv /sys/devices/system/cpu/cpu[1-9]*`; do
     if [ -e "$cpu/online" ]; then
         echo -n "$(basename $cpu), "
-        echo 0 > "$cpu/online" 2>/dev/null || echo "Failed to disable $cpu"
+	(echo 0 > "$cpu/online" 2>/dev/null || echo "Failed to disable $cpu")&
     fi
 done
 echo
diff --git a/setup/files/ocs/live-hook/udev/cpu_online b/setup/files/ocs/live-hook/udev/cpu_online
--- a/setup/files/ocs/live-hook/udev/cpu_online
+++ b/setup/files/ocs/live-hook/udev/cpu_online
@@ -7,7 +7,7 @@ echo "Enabling SMP-like behavior after udev was started... "
 for cpu in `ls -dv /sys/devices/system/cpu/cpu[1-9]*`; do
     if [ -e "$cpu/online" ]; then
         echo -n "$(basename $cpu), "
-        echo 1 > "$cpu/online" 2>/dev/null || echo "Failed to enable $cpu"
+	(echo 1 > "$cpu/online" 2>/dev/null || echo "Failed to enable $cpu")&
     fi
 done
 echo "done!"
